<div class="row">
    <div class="col-lg-6">
        <div class="form-group">
            <label>Email *</label>
            <input id="email" name="email" disabled=""
                   value="{{userInfo.email}}" type="text" class="form-control" />
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>First name *</label>
            <input id="name" name="name" type="text" ng-model="userInfo.firstName"
                   class="form-control required" />
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Gender *</label>
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-primary btn-sm
                                            {{userInfo.gender ? 'active' : ''}}"
                       ng-click="userInfo.gender=true">
                    <input type="radio" name="gender" value="1" /> Male
                </label>
                &nbsp;
                <label class="btn btn-outline btn-primary btn-sm
                                            {{!userInfo.gender ? 'active' : ''}}"
                       ng-click="userInfo.gender=false">
                    <input type="radio" name="gender" value="0" /> Female
                </label>
            </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>City *</label>
            <input id="city" name="city" ng-model="userInfo.city" type="text"
                   class="form-control required" />
        </div>
    </div>
    <div class="col-lg-6">
        <div class="form-group" style="visibility: hidden">
            <label>Last name *</label>
            <input id="surname2" name="surname2" type="text"
                   class="form-control" />
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Last name *</label>
            <input id="surname" name="surname" type="text" ng-model="userInfo.lastName"
                   class="form-control required" />
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Phone *</label>
            <input id="phone" name="phone" type="phone" ng-model="userInfo.phone"
                   class="form-control required" />
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Country *</label>
            <select class="form-control required" id="country" name="country"
                    ng-model="userInfo.country" ng-options="country.label for country in countries">
            </select>
        </div>
    </div>
</div>