<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Languages </th>
            <th>DTP software </th>
            <th>Price/Page <i class="fa fa-apple"></th>
            <th>Price/Page <i class="fa fa-windows"></i></th>
            <th>Price/Hour <i class="fa fa-apple"></th>
            <th>Price/Hour <i class="fa fa-windows"></i></th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>European/CE/Greek/Russian</td>
            <td>Indesign</td>
            <td>12.00</td>
            <td>10.00</td>
            <td>50.00</td>
            <td>40.00</td>
            <td><a href="#"><i class="fa fa-trash-o text-danger"></i></a></td>
        </tr>
        </tbody>
    </table>
</div>
<div class="text-center">
    <a data-toggle="modal" class="btn btn-outline btn-info" href="#modal-dtp">Add DTP prices</a>
</div>