<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Source Language </th>
            <th>Target Language </th>
            <th>Interpreting Service</th>
            <th>Price/Day</th>
            <th>Price/half-Day</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>English</td>
            <td>Chinese</td>
            <td>Consecutive</td>
            <td>5000</td>
            <td>4000</td>
            <td><a href="#"><i class="fa fa-trash-o text-danger"></i></a></td>
        </tr>
        </tbody>
    </table>
</div>
<div class="text-center">
    <a data-toggle="modal" class="btn btn-outline btn-success" href="#modal-interpreting">Add Interpreting prices</a>
</div>