
<! add language pair and price >
<div id="modal-translation" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Language pairs and prices</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Source Language *</label>
                                <select class="form-control required" name="sourceLanguage"
                                        ng-model="translationPrice.sourceLanguage"
                                        ng-options="language.name for language in languages">
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Target Language *</label>
                                <select class="form-control required" name="targetLanguage"
                                        ng-model="translationPrice.targetLanguage"
                                        ng-options="language.name for language in languages">
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Price/word *</label>
                                <input name="price" type="number" class="form-control required"
                                       ng-model="translationPrice.price">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-w-m btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-w-m btn-primary"
                    ng-click="submitTo('#modal-translation','#UpdateInfoController', 'saveTranslationPrice',
                                       translationPrice)"
                    >Save changes</button>
            </div>
        </div>
    </div>
</div>

<! add DTP price >
<div id="modal-dtp" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Add DTP prices</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Languages *</label>
                                <select class="form-control required" name="language"
                                        ng-model="desktopPrice.language"
                                        ng-options="language.name for language in languages">
                                </select>
                            </div>
                            <div class="form-group">
                                <label>DTP software *</label>
                                <select class="form-control required" name="software"
                                        ng-model="desktopPrice.software"
                                        ng-options="software.name for software in softwares">
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Price/Page (MAC) *</label>
                                <input name="priceMac" type="number" value="" class="form-control required"
                                       ng-model="desktopPrice.priceMac">
                            </div>
                            <div class="form-group">
                                <label>Price/Page (PC) *</label>
                                <input name="pricePc" type="number" value="" class="form-control required"
                                       ng-model="desktopPrice.pricePc">
                            </div>
                            <div class="form-group">
                                <label>Price/Hour (MAC) *</label>
                                <input name="priceHourMac" type="number" value="" class="form-control required"
                                       ng-model="desktopPrice.priceHourMac">
                            </div>
                            <div class="form-group">
                                <label>Price/Hour (PC) *</label>
                                <input name="priceHourPc" type="number" value="" class="form-control required"
                                       ng-model="desktopPrice.priceHourPc">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-w-m btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-w-m btn-primary"
                        ng-click="submitTo('#modal-dtp','#UpdateInfoController', 'saveDesktopPrice',
                                           desktopPrice)">Save changes</button>
            </div>
        </div>
    </div>
</div>

<! add interpreting price >
<div id="modal-interpreting" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Interpreting prices</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Source Language *</label>
                                <select class="form-control required" name="sourceLanguage"
                                        ng-model="interpretingPrice.sourceLanguage"
                                        ng-options="language.name for language in languages">
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Target Language *</label>
                                <select class="form-control required" name="targetLanguage"
                                        ng-model="interpretingPrice.targetLanguage"
                                        ng-options="language.name for language in languages">
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Interpreting Service *</label>
                                <select class="form-control required" name="service"
                                        ng-model="interpretingPrice.service"
                                        ng-options="service.name for service in services">
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Price/Day *</label>
                                <input name="priceDay" type="number" class="form-control required"
                                       ng-model="interpretingPrice.priceDay">
                            </div>
                            <div class="form-group">
                                <label>Price/Half-day *</label>
                                <input name="priceHalfDay" type="number" class="form-control required"
                                       ng-model="interpretingPrice.priceHalfDay">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-w-m btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-w-m btn-primary"
                        ng-click="submitTo('#modal-interpreting','#UpdateInfoController', 'saveInterpretingPrice',
                                           interpretingPrice)">Save changes</button>
            </div>
        </div>
    </div>
</div>