<h4><i class="fa fa-file-text"></i> <?php echo $this->translate('Resume') ?></h4>
<div class="hr-line-dashed"></div>
<div class="row">
    <div class="col-lg-12">
        <div ng-controller="AppController" ng-file-drop uploader="uploader" class="form-group">
            <label><?php echo $this->translate('CV upload') ?> </label>
            <!-- TODO: file upload not working here -->
            <table class="table">
                <tbody>
                <tr>
                    <td class="project-title">
                        <i class="fa fa-file-text"></i>&nbsp; <a href="#">cv.docx</a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-times-circle"></i></a>
                    </td>
                    <td class="project-title" width="10%">
                        <button type="button" class="btn btn-w-m btn-white btn-xs">
                            <i class="fa fa-cloud-upload">
                                <?php echo $this->translate('Upload') ?></i></button>
                        <input type="file" ng-file-select="" uploader="uploader" />
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="hr-line-dashed"></div>
        <input type="hidden" ng-model="resume.id" />
        <div class="form-group">
            <label><?php echo $this->translate('Working Experiences') ?></label>
            <summernote ng-model="resume.workingExperiences" class="summernote">

            </summernote>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label><?php echo $this->translate('Education') ?> </label>
            <summernote ng-model="resume.education" class="summernote">

            </summernote>
        </div>
        <div ng-show="freelancer" class="hr-line-dashed"></div>
        <div ng-show="freelancer" class="form-group">
            <label><?php echo $this->translate('Recommended') ?> </label>
            <input ng-model="resume.recommended" name="recommend" value=""
                   placeholder="Name/Email/Phone   " type="text" class="form-control">
        </div>
    </div>
</div>