<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Source Language </th>
            <th>Target Language </th>
            <th>Translation Price</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>English</td>
            <td>Chinese</td>
            <td>0.12</td>
            <td><a href="#"><i class="fa fa-trash-o text-danger"></i></a></td>
        </tr>
        </tbody>
    </table>
</div>
<div class="hr-line-dashed"></div>
<div class="text-center">
    <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-translation">Add Language pairs and prices</a>
</div>