<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Source Language </th>
            <th>Target Language </th>
            <th>Translation Price</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="translationPrice in translationPrices">
            <td>{{$index + 1}}</td>
            <td>{{translationPrice.sourceLanguage.name}}</td>
            <td>{{translationPrice.targetLanguage.name}}</td>
            <td>{{translationPrice.price}}</td>
            <td><a href="#" ng-click="deleteTranslationPrice($index)" onClick="return false;">
                <i class="fa fa-trash-o text-danger"></i>
                </a>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<div class="hr-line-dashed"></div>
<div class="text-center">
    <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-translation">Add Language pairs and prices</a>
</div>