
<!-- Le styles -->
<?php $this->headLink()
        ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
        ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/admin/user/update-info.js')
    ->prependScript("angularApp = angular.module('project', []);")
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js')
?>
<!-- Add custom style -->
<style type="text/css">
    .wizard-big.wizard > .content {
        min-height: 1200px;
    }

    .label {
        font-size: 15px;
    }

    h3 {
        font-size: 18px;
    }

    .float-e-margins .btn {
        margin-bottom: 0px;
    }
</style>
<!-- End custom style -->

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content" ng-controller="UpdateInfoController">
                    <h2>
                        Please finish your account information
                    </h2>

                    <p>
                        This example show how to use Steps with jQuery Validation plugin.
                    </p>

                    <form id="form" action="#" class="wizard-big">
                        <?php include __DIR__ . "/update-info/basic-info.phtml" ?>
                        <?php include __DIR__ . "/update-info/resource-type.phtml" ?>
                        <?php include __DIR__ . "/update-info/language-skill-price.phtml" ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div> <!-- close the container div -->
<div> <!-- open new temporary container -->

<!-- add language pair and price -->
<div id="modal-translation" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Language pairs and prices</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Source Language *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Target Language *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Price/word *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-w-m btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-w-m btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- add DTP price -->
<div id="modal-dtp" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Add DTP prices</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Languages *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option>European/CE/Greek/Russian</option>
                                    <option>SC/TC/JP/KO</option>
                                    <option>TH/VN</option>
                                    <option>Others</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>DTP software *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Price/Page (MAC) *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                            <div class="form-group">
                                <label>Price/Page (PC) *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                            <div class="form-group">
                                <label>Price/Hour (MAC) *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                            <div class="form-group">
                                <label>Price/Hour (PC) *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-w-m btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-w-m btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- add interpreting price -->
<div id="modal-interpreting" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Interpreting prices</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Source Language *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Target Language *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Interpreting Service *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option></option>
                                    <option>Simultaneous</option>
                                    <option>Consecutive</option>
                                    <option>Business</option>
                                    <option>Tourist</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Price/Day *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                            <div class="form-group">
                                <label>Price/Half-day *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-w-m btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-w-m btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>


<select class="multiselect" multiple="multiple">
    <option value="cheese">Cheese</option>
    <option value="tomatoes">Tomatoes</option>
    <option value="mozarella">Mozzarella</option>
    <option value="mushrooms">Mushrooms</option>
    <option value="pepperoni">Pepperoni</option>
    <option value="onions">Onions</option>
</select>

<script type="text/javascript">
    $(document).ready(function () {
        $('.multiselect').multiselect();
    });
</script>
