
<!-- Le styles -->
<?php $this->headLink()
        ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
        ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/admin/user/update-info.js')
    ->prependScript("angularApp = angular.module('project', []);")
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js')
?>
<!-- Add custom style -->
<style type="text/css">
    .wizard-big.wizard > .content {
        min-height: 1200px;
    }

    .label {
        font-size: 15px;
    }

    h3 {
        font-size: 18px;
    }

    .float-e-margins .btn {
        margin-bottom: 0px;
    }

    .resource-types .panel-body label{
        margin-right: 0.5em;
    }

    .multiselect-container{
        max-height: 250px;
        overflow-y: auto;
        overflow-x: hidden;
    }

</style>
<!-- End custom style -->

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content" id="UpdateInfoController" ng-controller="UpdateInfoController">
                    <h2 ng-show="!userInfo.profileUpdated">
                        Please finish your account information
                    </h2>
                    <h2 ng-show="userInfo.profileUpdated">
                        Update your account information
                    </h2>

                    <form id="form" action="#" class="wizard-big">
                        <?php include __DIR__ . "/update-info/basic-info.phtml" ?>
                        <?php include __DIR__ . "/update-info/resource-type.phtml" ?>
                        <?php include __DIR__ . "/update-info/language-skill-price.phtml" ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div> <!-- close the container div -->
<div> <!-- open new temporary container -->
    <?php include __DIR__ . "/update-info/modal.phtml" ?>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.multiselect').multiselect({
                numberDisplayed: 1
            });
        });
    </script>
