<?php $this->headTitle($this->translate('Login to PaperTask')) ?>
<style>
    .logo-name {
        font-size: 80px;
    }
</style>
<div class="middle-box loginscreen">
    <h3><?php echo $this->translate('Login to PaperTask') ?></h3>

    <form class="m-t" method="post" role="form" action="">
        <?php
        if($this->form->isHasNonElementMessages()){
            ?>
            <div class="form-group has-error">
                <?php

                foreach ($this->form->getNonElementMessages() as $scope => $messages){
                    foreach($messages as $message){
                        ?><div class="alert-<?php echo $scope;?>"><?php echo $message; ?></div><?php
                    }
                }
                ?>
            </div>
            <?php
        }
        foreach ($this->form->getElements() as $element): ?>
            <?php
            $messages = $element->getMessages()
            ?>
            <div class="form-group<?php if ($messages) echo " has-error" ?>">
                <?php if ($messages): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="alert-danger"><?php echo $message; ?></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php echo $this->formInput($element); ?>
            </div>
        <?php endforeach; ?>
        <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

        <h3><?php echo $this->translate('or Login with') ?></h3>

        <div class="col-lg-12 well">
            <a class="btn btn-success btn-facebook" href="<?php echo $this->url('user') ?>/login/social?provider=Facebook">
                <i class="fa fa-facebook"> </i> Facebook
            </a> &nbsp;&nbsp;
            <a class="btn btn-danger btn-google" href="<?php echo $this->url('user') ?>/login/social?provider=Google">
                <i class="fa fa-google"> </i> Google
            </a>
        </div>

        <a href="<?php echo $this->url('user') ?>/forgotPassword">
            <small><?php echo $this->translate('Forgot password?') ?></small>
        </a>
        <hr/>
        <p class="text-muted text-center">
            <small><?php echo $this->translate('Do not have an account?') ?></small>
        </p>
        <a class="btn btn-sm btn-white btn-block" href="<?php echo $this->url('user') ?>/register">
            <?php echo $this->translate('Create an account') ?>
        </a>
    </form>
</div>