<div ng-controller="ModalController" id="modalContainer"> <!-- open new temporary container -->
	
    <!-- add company -->
    <div id="modal-company" class="modal fade" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add Company</h4>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Company Name *</label>
                                    <input id="c-name" name="c-name" type="text" class="form-control required"
                                           ng-model="company.name">
                                </div>
                                <div class="form-group">
                                    <label>Telephone </label>
                                    <input id="c-tel" name="c-tel" type="text" class="form-control"
                                           ng-model="company.telephone">
                                </div>
                                <div class="form-group">
                                    <label>Fax </label>
                                    <input id="c-fax" name="c-fax" type="text" class="form-control"
                                           ng-model="company.fax">
                                </div>
                                <div class="form-group">
                                    <label>Address </label>
                                    <input id="c-address" name="c-address" type="text" class="form-control"
                                           ng-model="company.address">
                                </div>
                                <div class="form-group">
                                    <label>City *</label>
                                    <input id="c-city" name="c-city" type="text" class="form-control required"
                                           ng-model="company.city">
                                </div>
                                <div class="form-group">
                                    <label>Country *</label>
                                    <select class="form-control required" id="country" name="country" value=""
                                            ng-model="company.country"
                                            ng-options="country.label for country in countries">
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Website *</label>
                                    <input id="web" name="web" type="text" class="form-control required"
                                           ng-model="company.website">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-w-m btn-white" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-w-m btn-primary" ng-click="submitTo('#modal-company', '#EmployerController', 'saveCompany', company)">
                    	Save changes
                    </button>
                </div>
            </div>
        </div>
    </div>
    
</div>