<h4><i class="fa fa-puzzle-piece"></i> Staff Type</h4>
<div class="hr-line-dashed"></div>
<div class="form-group">
    <div data-toggle="buttons">
        <label class="btn btn-sm btn-outline btn-primary">
            <input type="radio" name="translator" value=""> Admin
        </label>
        &nbsp;
        <label class="btn btn-sm btn-outline btn-primary">
            <input type="radio" name="proofreader" value=""> General Manager
        </label>
        <br>
        <br>
        <label class="btn btn-sm btn-outline btn-primary">
            <input type="radio" name="translator" value=""> Financial Manager
        </label>
        <br>
        <br>
        <label class="btn btn-sm btn-outline btn-primary">
            <input type="radio" name="proofreader" value=""> Sales Director
        </label>
        &nbsp;
        <label class="btn btn-sm btn-outline btn-primary">
            <input type="radio" name="translator" value=""> Sales
        </label>
        <br>
        <br>
        <label class="btn btn-sm btn-outline btn-primary">
            <input type="radio" name="proofreader" value=""> Operation Manager
        </label>
        &nbsp;
        <label class="btn btn-sm btn-outline btn-primary">
            <input type="radio" name="translator" value=""> Project Manager
        </label>
        <br>
        <br>
        <label class="btn btn-sm btn-outline btn-primary">
            <input type="radio" name="proofreader" value=""> In-house Translator
        </label>
        &nbsp;
        <label class="btn btn-sm btn-outline btn-primary">
            <input type="radio" name="proofreader" value=""> In-house Editor/proofreader
        </label>
        &nbsp;
        <label class="btn btn-sm btn-outline btn-primary">
            <input type="radio" name="proofreader" value=""> In-house DTP
        </label>
        &nbsp;
        <label class="btn btn-sm btn-outline btn-primary">
            <input type="radio" name="proofreader" value=""> In-house Engineering
        </label>
        &nbsp;
    </div>

</div>