<h1>Languages/Skills/Prices</h1>
<fieldset>

    <div class="panel panel-info">
        <div class="panel-body">
            <h2><i class="fa fa-desktop"></i>&nbsp; Currency</h2>
            <br />
            <?php include "/../../user/currency-setup.phtml"; ?>
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-body">
            <h2><i class="fa fa-coffee"></i>&nbsp; Translation</h2>
            <div class="hr-line-dashed"></div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>Specialisms * &nbsp; </label>
                        <select class="form-control required multiselect" multiple="multiple"
                                ng-model="userInfo.TranslationSpecialisms"
                                ng-options="t.name for t in specialisms"
                                name="userTranslationSpecialisms" id="userTranslationSpecialisms">
                        </select>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>CAT Tools * &nbsp; </label>
                        <select class="form-control required multiselect" multiple="multiple"
                                ng-model="userInfo.TranslationCatTools"
                                ng-options="t.name for t in catTools"
                                name="userTranslationCatTools" id="userTranslationCatTools">
                        </select>
                    </div>
                </div>
            </div>
            <?php include "/../../user/translation-pair.phtml" ?>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-body">
            <h2><i class="fa fa-desktop"></i>&nbsp; Desktop Publishing</h2>
            <div class="hr-line-dashed"></div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>Operating System * &nbsp; </label>
                        <select class="form-control required multiselect" multiple="multiple"
                                ng-model="userInfo.DesktopOperatingSystems"
                                ng-options="t.name for t in operatingSystems"
                                name="userDesktopOperatingSystems" id="userDesktopOperatingSystems">
                        </select>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>CAT Tools * &nbsp; </label>
                        <select class="form-control required multiselect" multiple="multiple"
                                ng-model="userInfo.DesktopCatTools"
                                ng-options="t.name for t in catTools"
                                name="userDesktopCatTools" id="userDesktopCatTools">
                        </select>
                    </div>
                </div>
            </div>
            <?php include "/../../user/desktop-pair.phtml" ?>
        </div>
    </div>

    <div class="panel panel-success">
        <div class="panel-body">
            <h2><i class="fa fa-comments-o"></i>&nbsp; Interpreting</h2>
            <div class="hr-line-dashed"></div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Specialisms * &nbsp; </label>
                        <select class="form-control required multiselect" multiple="multiple"
                                ng-model="userInfo.InterpretingSpecialisms"
                                ng-options="t.name for t in specialisms"
                                name="userInterpretingSpecialisms" id="userInterpretingSpecialisms">
                        </select>
                    </div>
                </div>
            </div>
            <?php include "/../../user/interpreting-pair.phtml" ?>
        </div>
    </div>
</fieldset>