<div class="ibox">
    <div class="ibox-title">
        <h5><i class="fa fa-files-o"></i> Project Files </h5>
        <div class="ibox-tools" id="files">
            <input type="file" name="files[]"/>
        </div>
    </div>
    <div class="ibox-content">
        <div class="row">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>File Name</th>
                    <th>File Size</th>
                    <th>Time Stamp</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="file in project.files">
                    <td>{{$index + 1}}</td>
                    <td><a href="#">{{file.name}}</a></td>
                    <td class="text-right">{{file.size}}</td>
                    <td>{{file.time}}</td>
                    <td class="text-center child-is-link">
                        <i ng-click="removeFile($index)" class="fa fa-trash-o text-danger"></i>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>