<div class="ibox">
    <div class="ibox-title">
        <h4><i class="fa fa-sitemap"></i> Service Level <small>Project default service level</small></h4>
    </div>
    <div class="ibox-content wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <div data-toggle="buttons">
                        <label class="btn btn-outline btn-primary" ng-repeat="level in levels"
                               ng-click="project.serviceLevel=level">
                            <input class="required" type="radio" name="level" value="{{level.id}}"
                                   data-errorplace="element.parent().parent().after(error)"/> {{level.name}}
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 form-horizontal">
                <div class="form-group">
                    <label class="col-sm-6 control-label">Approximate duration *</label>
                    <div class="col-sm-3">
                        <input ng-model="project.duration" type="text" class="form-control required"
                            name="duration"/>
                    </div>
                    <span class="col-sm-3 control-label">Working days</span>
                </div>
            </div>
        </div>
    </div>
</div>