<div class="banner">
    <div class="container">
        <br><br>
        <div class="row">
            <h1 class="text-center" style="font-size: 60px;"><strong>GET IN TOUCH WITH PAPERTASK</strong></h1>
            <h3 class="text-center">PLEASE CONTACT US TO GET MORE INFORMATION ABOUT OUR SERVICES</h3>
            <br><br><br><br><br>
        </div>
    </div>
</div>
<div id="features" class="features">

    <div class="container">
        <div class="row">
            <form class="form-horizontal" role="form">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">First Name * </label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-4 control-label">Last Name *</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Phone Number</label>
                        <div class="col-sm-8">
                            <input type="number" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-4 control-label">Email Address *</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Company </label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-4 control-label">Job Title</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-2 control-label">Comments</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" rows="10"></textarea>
                        </div>
                    </div>
                </div>
                <br><br><br><br><br><br><br><br><br>
                <div class="col-sm-2"></div>
                <div class="col-sm-10 text-left">
                    <a href="javascript:;" type="submit" class="btn btn-primary btn-lg">Get In Touch </a>
                </div>
                <br><br><br><br>
            </form>
        </div>
    </div>
</div>