<?php $this->headTitle($this->translate('FREELANCER')) ?>
<div class="banner">
    <div class="container">
        <br><br>
        <div class="row">
            <h1 class="text-center" style="font-size: 80px;"><strong>
                    <?php echo $this->translate('WORK FREE!') ?></strong></h1>
            <br><br>
            <a href="<?php echo $this->url('user') ?>/register/freelancer/"
               target="_blank" class="btn btn-download btn-lg">
                <?php echo $this->translate('Register As a Freelancer, Now!') ?></a>
            <br><br><br>
        </div>
    </div>
</div>
<div class="features">
    <div class="container">
        <h1 class="text-center" style="font-size: 40px;">
            <?php echo $this->translate('Work With PaperTask') ?></h1>
        <br><br><br>
        <div class="row">
            <div class="feature-item col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <button type="button" class="btn btn-primary btn-block btn-lg">1.
                            <?php echo $this->translate('Register') ?></button>
                        <br>
                        <p><?php echo $this->translate('Sign up PaperTask, you may work with PaperTask together for translation jobs.') ?></p>
                        <br><br>
                    </div>
                </div>
            </div>
            <div class="feature-item col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <button type="button" class="btn btn-primary btn-block btn-lg">2.
                            <?php echo $this->translate('Qualify') ?></button>
                        <br>
                        <p><?php echo $this->translate('If you want to get a job here, you must pass our certification, after pass the evaluation of our senior translators, you can get the translation tasks.') ?></p>
                    </div>
                </div>
            </div>
            <div class="feature-item col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <button type="button" class="btn btn-primary btn-block btn-lg">3.
                            <?php echo $this->translate('Work Free') ?></button>
                        <br>
                        <p><?php echo $this->translate('In success pass our testing, you can get the translation jobs and work with us, look forward to your joining!') ?></p>
                        <br>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="row text-center">
            <a href="<?php echo $this->url('user') ?>/register/freelancer/" target="_blank" class="btn btn-primary btn-lg">
                <?php echo $this->translate('Register As a Freelancer, Now!') ?></a>
        </div>
        <br><br><br>
    </div>
</div>