<div class="banner">
    <div class="container">
        <br><br>
        <div class="row">
            <div class="feature-item col-md-7 text-left">
                <br>
                <i class="fa fa-chevron-circle-right" style=" color: #fff; font-size: 24px;"> &nbsp;&nbsp;The new mode of translation services</i>
                <br><br>
                <i class="fa fa-chevron-circle-right" style=" color: #fff; font-size: 24px;"> &nbsp;&nbsp;High quality human translation</i>
                <br><br>
                <i class="fa fa-chevron-circle-right" style=" color: #fff; font-size: 24px;"> &nbsp;&nbsp;20,000+ professional translators worldwide</i>
                <br><br>
                <i class="fa fa-chevron-circle-right" style=" color: #fff; font-size: 24px;"> &nbsp;&nbsp;Support more than 70 languages</i>
                <br><br>
                <i class="fa fa-chevron-circle-right" style=" color: #fff; font-size: 24px;"> &nbsp;&nbsp;New smart quotation system, without human intervention</i>
                <br><br>
                <i class="fa fa-chevron-circle-right" style=" color: #fff; font-size: 24px;"> &nbsp;&nbsp;Guaranteed high quality and lowest price in the market</i>
            </div>
            <div class="feature-item col-md-5 text-center">
                <img src="assets/home1.png" alt="PaperTask.com" class="preview-img">
            </div>
        </div>
        <br><br>
        <a href="javascript:;" target="_blank" class="btn btn-download btn-lg">Instant Quote / Order Translation</a>
        <br><br><br>
    </div>
</div>
<div class="features">
    <h1 class="text-center">Globalization people-powered translation cloud platform </h1>
    <br>
    <div class="container">
        <div class="col-lg-12 text-center">
            <div class="detail-desc">
                <p style="font-size: 16px;">You can easily order files or text which need to be translated through our website. Our platform will instantly at your service. In the first task, experienced PaperTask project manager will assign it the job to the qualified translator(s) based on the field of your job, and add the translators to your resource group, so they will take over in a few minutes, and complete the translation. For your subsequent jobs, the platform will automatically assign it to the translators in your resource group.</p>
            </div>
        </div>
    </div>
</div>
<div class="details">
    <ul class="list-details list-unstyled">
        <li>
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <h2 style="font-size: 35px; line-height: 40px;">Language Quality Assurance</h2>
                        <p>
                        <h3 style="font-size: 20px;">While Ensuring the Translation Speed, Our Language Quality Assurance benefits you by:</h3>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-check color-green"></i> &nbsp;Delivering translation quality</li>
                            <li><i class="fa fa-check color-green"></i> &nbsp;Facilitating formal feedback between your organization and the linguist</li>
                            <li><i class="fa fa-check color-green"></i> &nbsp;Providing consistent linguistic quality management across multiple languages</li>
                            <li><i class="fa fa-check color-green"></i> &nbsp;Offering measurable and independent linguistic quality assessments</li>
                        </ul>
                        </p>
                    </div>
                    <div class="col-md-5 detail-img">
                        <br>
                        <img src="assets/quality-control.png" alt="Quality">
                    </div>
                </div>
            </div>
        </li>
        <li class="alt">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 detail-img" align="left">
                        <br>
                        <img src="assets/crowsourcing.png" alt="Reliable">
                    </div>
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-7">
                        <h2 style="font-size: 35px; line-height: 40px;">Reliable, consistent Quality in large Volume translation</h2>
                        <p>
                        <h3 style="font-size: 20px;">Quality Control for Large Scale Translation Project</h3>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-check color-green"></i> &nbsp;Rigorous and meticulous review, both technical and editorial, confirms complete accuracy, appropriateness, and consistency of all translations.</li>
                            <li><i class="fa fa-check color-green"></i> &nbsp;PaperTask maintains access to current and specific industry-related terminology and lexicons.</li>
                            <li><i class="fa fa-check color-green"></i> &nbsp;Memory technology is utilized by PaperTask platform, allowing the company to use previously translated material.</li>
                        </ul>
                        </p>
                    </div>
                </div>
            </div>
        </li>
        <li>
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <h2 style="font-size: 35px; line-height: 40px;">Feature-rich Localisation/Translation Management Platform</h2>
                        <p>
                        <h3 style="font-size: 20px;">While Ensuring the Translation Speed, Our Language Quality Assurance benefits you by:</h3>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-check color-green"></i> Collaborative translation shortens the translation cycle, improving delivery times by 50% or better!</li>
                            <li><i class="fa fa-check color-green"></i> The delivery phase, as well as other factors like cost tracking and invoicing, are all largely automated in PaperTask.</li>
                            <li><i class="fa fa-check color-green"></i> Continuous Dynamic Translation by PaperTask is one of the most advanced solution on the market today. Project setup, deadline calculations, translator assignments, document revisions, and job kick-offs are all automated.</li>
                            <li><i class="fa fa-check color-green"></i> PaperTask helps clients manage their translators, keep track of their specialty domains, and keep records about performance.</li>
                            <li><i class="fa fa-check color-green"></i> Client invoices are generated automatically. Customers can always view projects payment status, spending reports, download invoices directly.</li>
                        </ul>
                        </p>
                    </div>
                    <div class="col-md-5 detail-img">
                        <br><br><br><br><br>
                        <img src="assets/platform.png" alt="PaperTask Platform">
                    </div>
                </div>

            </div>
        </li>
    </ul>
</div>
<div class="features">
    <div class="container">
        <div class="col-lg-12 text-center">
            <div class="detail-desc">
                <a href="javascript:;" target="_blank" class="btn btn-primary btn-lg">Instant Quote / Order Translation</a>
            </div>
        </div>
    </div>
</div>