<?php $this->headTitle($this->translate('Languages and Prices')) ?>
<?php
$this->headScript()
    ->prependFile($this->basePath() . '/js/landing/languages.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependScript("angularApp = angular.module('languages', []);")
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/angular.min.js')
?>
<?php
$this->inlineScript()
    ->prependScript("
    <script>if(typeof(angular) != 'undefined' && typeof(angularApp) == 'undefined'){
        var angularApp = angularApp || angular.module('languages', []);
    }</script>
    ")
?>
<div ng-app="languages" id="languagesController" ng-controller="languagesController">
<div class="banner">
    <div class="container">
        <br><br>
        <div class="row">
            <h1 class="text-center"><?php echo $this->translate('PLEASE CHECK OUT THE LANGUAGES WE SUPPORT.') ?></h1>
            <h3 class="text-center">
                <?php echo $this->translate('WE’RE HONEST ABOUT QUALITY. AND WE OFFER ALL MAJOR LANGUAGES FOR
                TRANSLATION.') ?></h3>
            <br>
            <form name="showPriceForm" class="form-horizontal" role="form">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate('Source Language') ?></label>
                        <div class="col-sm-8">
                            <select ngChange="updateTargetLanguages()" ng-model="params.sourceLanguage"
                                    required name="sourceLanguage" class="form-control required">
                                <option value=""><?php echo $this->translate('Please select') ?></option>
                                <option ng-repeat="id in sourceLanguages" value="{{id}}">
                                    {{languages[id]}}
                                </option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-4 control-label">Target Language</label>
                        <div class="col-sm-8">
                            <select ng-model="params.targetLanguage" required name="targetLanguage"
                                    class="form-control required">
                                <option value=""><?php echo $this->translate('Please select') ?></option>
                                <option ng-repeat="id in targetLanguages" value="{{id}}">
                                    {{languages[id]}}
                                </option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Word Count</label>
                        <div class="col-sm-8">
                            <input name="wordCount" ng-model="params.wordCount" type="number"
                                   class="form-control required" required>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-4 control-label">Choose Currency</label>
                        <div class="col-sm-8">
                            <select ng-model="params.currency" name="currency" required class="form-control required">
                                <option value="USD">USD</option>
                                <option value="CNY">CNY</option>
                            </select>
                        </div>
                    </div>
                </div>
                <br><br><br><br><br><br><br><br><br>
                <button type="submit" ng-click="showPrice()" class="btn btn-download btn-lg">Show Price </button>
                <br><br><br><br>

            </form>
        </div>
    </div>
</div>
<div id="features" class="features hidden">

    <div class="container">
        <div class="row">
            <div class="feature-item col-md-4 text-center">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Professional</h4>
                        <p><em>Fast translation by native speakers</em></p>
                    </div>
                    <div class="panel-body">
                        <div class="text-left">
                            <li> Emails, Letters</li>
                            <li> Daily content, social media posts</li>
                            <li> User reviews, user generated content</li>
                            <li> Internal communication, customer support</li>
                        </div>
                        <hr />
                        <p style="font-size: 35px;"> CNY {{price.professionalPrice*params.wordCount}}</p>
                        <small>CNY {{price.professionalPrice}} / Word</small>
                        <hr />
                        <a href="javascript:;" target="_blank" class="btn btn-primary btn-lg">Order Now </a>
                    </div>
                </div>
            </div>
            <div class="feature-item col-md-4 text-center">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Business</h4>
                        <p><em>Professional quality translation plus proofreading</em></p>
                    </div>
                    <div class="panel-body">
                        <div class="text-left">
                            <li> Application/introduction, website localization</li>
                            <li> Business presentations, reports, articles</li>
                            <li> Instructions, manuals, guidelines</li>
                            <li> Points translation, product description</li>
                        </div>
                        <hr />
                        <p style="font-size: 35px;"> CNY {{price.businessPrice*params.wordCount}}</p>
                        <small>CNY {{price.businessPrice}} / Word</small>
                        <hr />
                        <a href="javascript:;" target="_blank" class="btn btn-primary btn-lg">Order Now </a>
                    </div>
                </div>
            </div>
            <div class="feature-item col-md-4 text-center">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Premium</h4>
                        <p><em>Professional plus extra proofreading</em></p>
                    </div>
                    <div class="panel-body">
                        <div class="text-left">
                            <li> Posters</li>
                            <li> Webpage, Webpage copy</li>
                            <li> News release</li>
                            <li> Promotional/marketing materials</li>
                        </div>
                        <hr />
                        <p style="font-size: 35px;"> CNY {{price.premiumPrice*params.wordCount}}</p>
                        <small>CNY {{price.premiumPrice}} / Word</small>
                        <hr />
                        <a href="javascript:;" target="_blank" class="btn btn-primary btn-lg">Order Now </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>