<div class="banner">
    <div class="container">
        <br><br>
        <div class="row">
            <h1 class="text-center">PLEASE CHECK OUT THE LANGUAGES WE SUPPORT.</h1>
            <h3 class="text-center">WE’RE HONEST ABOUT QUALITY. AND WE OFFER ALL MAJOR LANGUAGES FOR TRANSLATION.</h3>
            <br>
            <form class="form-horizontal" role="form">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Source Language</label>
                        <div class="col-sm-8">
                            <select class="form-control">
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-4 control-label">Target Language</label>
                        <div class="col-sm-8">
                            <select class="form-control">
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Word Count</label>
                        <div class="col-sm-8">
                            <input type="number" class="form-control" value="1000">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-4 control-label">Choose Currency</label>
                        <div class="col-sm-8">
                            <select class="form-control">
                                <option>USD</option>
                                <option>CNY</option>
                            </select>
                        </div>
                    </div>
                </div>
                <br><br><br><br><br><br><br><br><br>
                <a href="javascript:;" target="_blank" class="btn btn-download btn-lg">Show Price </a>
                <br><br><br><br>

            </form>
        </div>
    </div>
</div>
<div id="features" class="features">

    <div class="container">
        <div class="row">
            <div class="feature-item col-md-4 text-center">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Professional</h4>
                        <p><em>Fast translation by native speakers</em></p>
                    </div>
                    <div class="panel-body">
                        <div class="text-left">
                            <li> Emails, Letters</li>
                            <li> Daily content, social media posts</li>
                            <li> User reviews, user generated content</li>
                            <li> Internal communication, customer support</li>
                        </div>
                        <hr />
                        <p style="font-size: 35px;"> CNY 1289.87</p>
                        <small>CNY 0.07 / Word</small>
                        <hr />
                        <a href="javascript:;" target="_blank" class="btn btn-primary btn-lg">Order Now </a>
                    </div>
                </div>
            </div>
            <div class="feature-item col-md-4 text-center">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Business</h4>
                        <p><em>Professional quality translation plus proofreading</em></p>
                    </div>
                    <div class="panel-body">
                        <div class="text-left">
                            <li> Application/introduction, website localization</li>
                            <li> Business presentations, reports, articles</li>
                            <li> Instructions, manuals, guidelines</li>
                            <li> Points translation, product description</li>
                        </div>
                        <hr />
                        <p style="font-size: 35px;"> CNY 1289.87</p>
                        <small>CNY 0.07 / Word</small>
                        <hr />
                        <a href="javascript:;" target="_blank" class="btn btn-primary btn-lg">Order Now </a>
                    </div>
                </div>
            </div>
            <div class="feature-item col-md-4 text-center">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Premium</h4>
                        <p><em>Professional plus extra proofreading</em></p>
                    </div>
                    <div class="panel-body">
                        <div class="text-left">
                            <li> Posters</li>
                            <li> Webpage, Webpage copy</li>
                            <li> News release</li>
                            <li> Promotional/marketing materials</li>
                        </div>
                        <hr />
                        <p style="font-size: 35px;"> CNY 1289.87</p>
                        <small>CNY 0.07 / Word</small>
                        <hr />
                        <a href="javascript:;" target="_blank" class="btn btn-primary btn-lg">Order Now </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>