<div class="banner">
    <div class="container">
        <div class="row">
            <h1 class="text-center" style="font-size: 60px;"><strong>ORDER YOUR TRANSLATION</strong></h1>
            <h3 class="text-center">PLEASE FOLLOW THE STEPS TO PLACE AN ORDER</h3>
            <br><br>
        </div>
    </div>
</div>
<div id="features" class="features">

<div class="container">
<div class="row">
<div class="col-lg-8">
<form class="form-horizontal" role="form">

<div class=" form-group">
    <div class="col-md-12">
        <ul class="nav nav-pills nav-justified thumbnail setup-panel">
            <li class="active"><a href="#step-1">
                    <h4 class="list-group-item-heading">Step 1</h4>
                    <p class="list-group-item-text">Upload the file(s)</p>
                </a></li>
            <li class="disabled"><a href="#step-2">
                    <h4 class="list-group-item-heading">Step 2</h4>
                    <p class="list-group-item-text">Select Languages and Quality</p>
                </a></li>
            <li class="disabled"><a href="#step-3">
                    <h4 class="list-group-item-heading">Step 3</h4>
                    <p class="list-group-item-text">Confirm Your Information</p>
                </a></li>
        </ul>
    </div>
</div>

<div class=" setup-content" id="step-1">

    <div class="col-md-12 well">
        <p>We accept the following files, under <span class="text-danger">50MB</span> size:</p>
        <small><strong>Excel</strong> (.xls, .xlsx, .xlsm), <strong>Word</strong> (.doc, .docx), <strong>PowerPoint</strong> (.ppt, .pptx), <strong>Acrobat</strong> (.pdf), <strong>Open Office</strong> (.odt), <strong>Rich Text Format</strong> (.rtf), <strong>Plain text</strong> (.txt)</small>
        <br><br>
        <div class="col-md-4">
                        <span class="btn btn-primary btn fileinput-button">
                          <i class="fa fa-cloud-upload"></i>
                          <span>Select files</span>
                          <input id="fileupload" type="file" name="files[]" multiple>
                        </span>
        </div>
        <div class="col-md-8">
            <p></p>
            <div class="progress progress-bar-default">
                <div style="width: 43%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="43" role="progressbar" class="progress-bar">
                    <span class="sr-only">43% Complete (success)</span>
                </div>
            </div>
        </div>
        <br><br><br>
        <div class="project-list">
            <table class="table table-hover">
                <tbody>
                <tr>
                    <td class="project-title">
                        file name1.doc
                    </td>
                    <td class="project-completion text-right">
                        888 words
                    </td>
                    <td class="project-actions text-right">
                        <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                    </td>
                </tr>
                <tr>
                    <td class="project-title">
                        file name1.doc
                    </td>
                    <td class="project-actions text-right">
                        888 words
                    </td>
                    <td class="project-actions text-right">
                        <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <hr>
        <div class="text-center">
            <button id="activate-step-2" class="btn btn-primary btn-lg">Next</button> <!-- next button show after at least one file is uploaded -->
        </div>
    </div>
</div>
<div class=" setup-content" id="step-2">
    <div class="col-md-12 well">
        <div class="row">
            <div class="col-md-3">
                <h5> Select Currency</h5>
                <div data-toggle="buttons"> <!-- here do a judgement, if page load in chinese, then defaule currency is CNY, otherwise USD -->
                    <label class="btn btn-outline btn-primary">
                        <input type="radio" name="cny" value="" /> CNY
                    </label>
                    <label class="btn btn-outline btn-primary">
                        <input type="radio" name="usd" checked value="" /> USD
                    </label>
                </div>
            </div>
            <div class="col-md-6">
                <h5> Select Quality Level</h5>
                <div data-toggle="buttons"> <!-- here do a judgement, if page load in chinese, then defaule currency is CNY, otherwise USD -->
                    <label class="btn btn-outline btn-primary">
                        <input type="radio" name="prof" value="" /> Professional <i class="fa fa-question-circle"></i>
                    </label>
                    <label class="btn btn-outline btn-primary">
                        <input type="radio" name="business" value="" /> Business <i class="fa fa-question-circle"></i>
                    </label>
                    <label class="btn btn-outline btn-primary">
                        <input type="radio" name="premium" value="" /> Premium <i class="fa fa-question-circle"></i>
                    </label>
                </div>
            </div>
            <div class="col-md-3">
                <h5> Translate Graphics</h5>
                <div data-toggle="buttons"> <!-- here put it in default NO -->
                    <label class="btn btn-outline btn-primary">
                        <input type="radio" name="cny" value="" /> YES
                    </label>
                    <label class="btn btn-outline btn-primary">
                        <input type="radio" name="usd" checked value="" /> NO
                    </label>
                </div>
            </div>
        </div>


        <hr>
        <div class="row">
            <div class="col-md-6">
                <h4> Translate From *</h4>
                <select class="form-control" name="">
                    <option>Select Source Language</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                </select>
            </div>
            <div class="col-md-6">
                <h4> Translate To *</h4>
                <select class="form-control" name="">
                    <option>Add Target Languages</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                </select>
            </div>
        </div>
        <br>
        <div class="project-list">
            <table class="table table-hover">
                <tbody>
                <tr>
                    <td class="project-status">
                        <span class="label label-primary">Japanese</span>
                    </td>
                    <td class="project-title text-center">
                        <strong>888 (words) &nbsp;&nbsp;&nbsp;&nbsp; x &nbsp;&nbsp;&nbsp;&nbsp; CNY 0.12 &nbsp;&nbsp;&nbsp;&nbsp; = &nbsp;&nbsp;&nbsp;&nbsp; CNY 120.87</strong>
                    </td>
                    <td class="project-actions text-right">
                        <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                    </td>
                </tr>
                <tr>
                    <td class="project-status">
                        <span class="label label-primary">Korean</span>
                    </td>
                    <td class="project-title text-center">
                        <strong>888 (words) &nbsp;&nbsp;&nbsp;&nbsp; x &nbsp;&nbsp;&nbsp;&nbsp; CNY 0.12 &nbsp;&nbsp;&nbsp;&nbsp; = &nbsp;&nbsp;&nbsp;&nbsp; CNY 120.87</strong>
                    </td>
                    <td class="project-actions text-right">
                        <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <hr>
        <div class="text-center">
            <button id="" class="btn btn-primary btn-lg">Previous</button>
            <button id="activate-step-3" class="btn btn-primary btn-lg">Next</button>
        </div>
    </div>
</div>
<div class="setup-content" id="step-3">
    <div class="well">

        <form class="form-horizontal" role="form">
            <div class="row"> <!-- here need ajax verify to see if the email address is exist, if no show below infor to create a new account -->
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Email *</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" value="" placeholder="Email Address">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-5 control-label">Need Fapiao *</label>
                        <div class="col-sm-7">
                            <div data-toggle="buttons"> <!-- here IF YES, THEN SHOW TITLE, "NO" = HIDE TITLE, by default "NO"-->
                                <label class="btn btn-outline btn-primary">
                                    <input type="radio" name="" value="" /> YES
                                </label>
                                <label class="btn btn-outline btn-primary">
                                    <input type="radio" name="" value="" /> NO
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row"> <!-- here need ajax verify to see if the email address is exist, if no show below infor to create a new account -->
                <div class="col-sm-12">
                    <div class="form-group">
                        <label class="col-sm-2 control-label"> Title *</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" value="" placeholder="Your Chinese Company Title for Issue FAPIAO">
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <div class="form-group">
                        <label class="col-sm-2 control-label"> Address *</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" value="" placeholder="Your Mailing Address">
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Last Name *</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" value="" placeholder="Last Name">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-4 control-label">First Name *</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" value="" placeholder="First Name">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Password *</label>
                        <div class="col-sm-8">
                            <input type="password" class="form-control" value="" placeholder="Type Your Password">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Cellphone *</label>
                        <div class="col-sm-8">
                            <input type="number" class="form-control" value="" placeholder="Your Cellphone/Landline">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-4 control-label">Company</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" value="" placeholder="Your Company Full Name">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-4 control-label">Country</label>
                        <div class="col-sm-8">
                            <select class="form-control">
                                <option></option>
                                <option>China</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <hr>
        <div class="text-center"> <!-- if second step choose NO to translate graphic, then show this button -->
            <button id="" class="btn btn-primary btn-lg">Pay and Start to Translate</button>
        </div>
        <div class="text-center"> <!-- if second step choose yes to translate graphic, then show this button -->
            <button id="" class="btn btn-primary btn-lg">Request a Quote</button>
        </div>
    </div>

</div>

</form>
</div>
<div class="col-lg-4 well">
    <h1 class="text-center">Order Information</h1>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>3 iterms</th> <!-- before iterms, put the number of files uploaded -->
            <th class="text-right"> 888 words</th>
        </tr>
        <tr>
            <th>Languages</th>
            <th class="text-right">4</th> <!-- target languages number -->
        </tr>
        <tr>
            <th>Quality Level</th>
            <th class="text-right"><span class="label label-primary">Business</span> CNY 0.12/Word</th>
        </tr>
        </thead>
    </table>
    <br><br>
    <table class="table">
        <thead>
        <tr>
            <th>Iterms Total</th>
            <th class="text-right">CNY 1200.88</th>
        </tr>
        <tr>
            <th>Tax</th>
            <th class="text-right">CNY 200.88</th>
        </tr>
        <tr style="font-size: 22px;">
            <th>Total</th>
            <th class="text-right">CNY 1200.88</th>
        </tr>
        </thead>
    </table>
    <p>Estimated delivery <strong>34 hours.</strong></p> <!-- this hour based on the word count of the files, algorithm is estimate time = total word count / 2000 = number of hours, if the result is 1.2, then show 2, if 1.7, show 2 also-->
</div>
</div>

</div>
</div>