<?php $this->headTitle($this->translate('Project detail')) ?>
<!-- Le styles -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.js')
    ->prependFile($this->basePath() . '/js/admin/project/project-detail.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload']);")
    ->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
    //->prependFile($this->basePath() . '/js/plugins/datapicker/bootstrap-datepicker.js')
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js')
?>
<div class="row">
<div class="col-lg-12">
<div class="ibox" ng-controller="ProjectDetailController">
<div class="ibox-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="m-b-md">
                <a data-toggle="collapse" href="#edit_project" class="btn btn-danger btn-xs pull-right"><i class="fa fa-edit"></i><?php echo $this->translate('Edit Project') ?></a>
                <h2><span class="text-info">{{ project.id }}</span> - <?php echo $this->translate('Project Reference') ?>
                    {{ project.reference }}</h2>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-lg-5">
            <dl class="dl-horizontal">
                <dt>Status:</dt> <dd><span class="label label-{{ project.status.decorator }}">{{ project.status.name }}</span> </dd>
                <br>
                <dt>Client Contact:</dt> <dd><a href="#" class="text-navy"> {{ project.client.lastName }}, {{ project.client.firstName }}</a></dd>
                <dt>Client Company:</dt> <dd>{{ project.client.company.name }}</dd>
                <br>
                <dt>Start Date:</dt> <dd>{{ DateFormatter.format(project.startDate) }}</dd>
                <dt>Due Date:</dt> <dd>{{ DateFormatter.format(project.dueDate) }}</dd>
                <br>
                <br>
                <dt>Source Language:</dt> <dd><code>{{ project.sourceLanguage.name }}</code></dd>
                <br>
            </dl>
        </div>
        <div class="col-lg-7">
            <dl class="dl-horizontal" >
                <dt>Priority:</dt> <dd><span class="label label-{{ project.priority.decorator }}">{{ project.priority.name }}</span> </dd>
                <br>
                <dt>Sales:</dt> <dd>{{ project.sale.name }}</dd>
                <dt>Project Manager:</dt> <dd>{{ project.pm.name }}</dd>
                <br>
                <dt>Field:</dt> <dd>{{ project.field.name }}</dd>
                <dt>Project Level:</dt> <dd><code>{{ project.level.name }}</code> </dd>
                <dt>Type:</dt>
                <dd>
                    <div class="tooltip-demo">
                        <span ng-repeat="type in TypeList.getProjectTypes(project)">
                            <code {{ TypeList.getTypeAttrs(type) }}>{{ TypeList.getDisplayName(type) }}</code>
                        </span>
                    </div>
                </dd>
                <br>
                <dt>Target Languages:</dt> <dd>
                    <code ng-repeat="language in project.targetLanguages">{{ language.name }}</code>
                </dd>
            </dl>
        </div>
    </div>
<div class="row">
    <div class="col-lg-12">
        <div id="edit_project" class="panel-collapse collapse faq-answer">
            <form method="" class="form-horizontal">
                <div class="row form-horizontal">

                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Reference *</label>
                            <div class="col-sm-9">
                                <input id="" name="" value="Project reference" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="form-group" id="ordered_date">
                            <label class="col-sm-3 control-label">Start Date *</label>
                            <div class="col-sm-9">
                                <div class="input-append date form_datetime" >
                                    <input class="form-control" type="text" value="" readonly>
                                    <span class="add-on"><i class="icon-remove"></i></span>
                                    <span class="add-on"><i class="icon-th"></i></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Field *</label>
                            <div class="col-sm-9">
                                <select class="form-control required valid" id="" name="" value="" aria-required="true">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Sales </label>
                            <div class="col-sm-9">
                                <select class="form-control required valid" id="country" name="country" value="" aria-required="true">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Priority *</label>
                            <div class="col-sm-9">
                                <div data-toggle="buttons">
                                    <label class="btn btn-outline btn-primary btn-sm">
                                        <input type="radio" name="gender" value="male"> Normal
                                    </label>
                                    &nbsp;
                                    <label class="btn btn-outline btn-danger btn-sm">
                                        <input type="radio" name="gender" value="female"> High
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group" id="due_date">
                            <label class="col-sm-3 control-label">Due Date *</label>
                            <div class="col-sm-9">
                                <div class="input-append date form_datetime" >
                                    <input class="form-control" type="text" value="" readonly>
                                    <span class="add-on"><i class="icon-remove"></i></span>
                                    <span class="add-on"><i class="icon-th"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">Client *</label>
                            <div class="col-sm-9">
                                <select class="form-control required valid" id="" name="" value="" aria-required="true">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">PM *</label>
                            <div class="col-sm-9">
                                <select class="form-control required valid" id="" name="" value="" aria-required="true">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-right tooltip-demo">
                    <a href="#" class="btn btn-sm btn-primary"><i class="fa fa-save"></i> Update</a>
                </div>
            </form>
        </div>
    </div>
</div>


<div class="row m-t-sm">
<div class="col-lg-12">
<div class="panel blank-panel">
<div class="panel-heading">
    <div class="panel-options">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tasks" data-toggle="tab"><span class="label label-warning">8</span> Tasks</a></li>
            <li class=""><a href="#message" data-toggle="tab"><span class="label label-warning">6</span> Messages & Activities</a></li>
            <li class=""><a href="#files" data-toggle="tab"><span class="label label-danger">2</span> Project Files</a></li>
            <li class=""><a href="#feedback" data-toggle="tab"> Feedbacks</a></li>
            <li class=""><a href="#quote" data-toggle="tab"> Quote</a></li> <!-- if the project status is quote, then show quote, other wise hide quote -->
            <li class=""><a href="#invoice" data-toggle="tab"> Invoice</a></li> <!-- if the status is not quote, then show invoice -->
        </ul>
    </div>
</div>

<div class="panel-body">

<div class="tab-content">
<div class="tab-pane active" id="tasks">
<form class="form-horizontal">
    <div class="form-group">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-md-4">
                    <select class="form-control" name="account">
                        <option>Select Task Type</option>
                        <option>Translation (Use TM)</option>
                        <option>DTP</option>
                        <option>Proofreading</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <select class="form-control" name="account">
                        <option>Select Language Pair</option>
                        <option>English to Chinese</option>
                        <option>English to Japanese</option>
                    </select>
                </div>
                <div class="col-md-4"><button class="btn btn-primary" type="submit">Create New Task</button></div>
            </div>
        </div>
    </div>
</form>

<div class="hr-line-dashed"></div>
<div class="project-list">
    <table class="table table-hover">
        <tbody>
        <tr>
            <td class="project-status">
                <span class="label label-default">Completed</span> <i class="fa fa-usd"></i>
            </td>
            <td class="project-title">
                <strong>project referencereferencereference </strong>
                <br>
                <strong class="text-info">88888888-01</strong>  |  <code>English</code> <i class="fa fa-arrow-right"></i> <code>Japanese</code> <i class="fa fa-paperclip"></i> <!-- paperclip means freelancer uploaded the translated file -->
            </td>

            </td>
            <td class="project-title">
                <a href=""><strong>freelancer, Name</strong></a>
                <div class="tooltip-demo">
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation with Translation Memory">TM</code>  |  2014.Sep.08 -  2014.Oct.28
                </div>
            </td>
            <td class="project-actions">
                <div class="tooltip-demo">
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="View Task Details" class="btn btn-white btn-xs"><i class="fa fa-folder"></i> </a>
                </div>
            </td>
        </tr>
        <tr>
            <td class="project-status">
                <span class="label label-default">Completed</span>
            </td>
            <td class="project-title">
                <strong>project referencereferencereference </strong>
                <br>
                <strong class="text-info">88888888-02</strong>  |  <code>English</code> <i class="fa fa-arrow-right"></i> <code>Japanese</code> <i class="fa fa-paperclip"></i> <!-- paperclip means freelancer uploaded the translated file -->
            </td>

            </td>
            <td class="project-title">
                <a href=""><strong>freelancer, Name</strong></a>
                <div class="tooltip-demo">
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation with Translation Memory">TM</code>  |  2014.Sep.08 -  2014.Oct.28
                </div>
            </td>
            <td class="project-actions">
                <div class="tooltip-demo">
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="View Task Details" class="btn btn-white btn-xs"><i class="fa fa-folder"></i> </a>
                </div>
            </td>
        </tr>
        <tr>
            <td class="project-status">
                <span class="label label-warning">5</span> <span class="label label-primary">Ongoing</span>
            </td>
            <td class="project-title">
                <strong>project referencereferencereference </strong>
                <br>
                <strong class="text-info">88888888-03</strong>  |  <code>English</code> <i class="fa fa-arrow-right"></i> <code>Chinese</code>
            </td>

            </td>
            <td class="project-title">
                <a href=""><strong>freelancer, Name</strong></a>
                <div class="tooltip-demo">
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation without Translation Memory">No-TM</code>  |  2014.Sep.08 -  2014.Oct.28
                </div>
            </td>
            <td class="project-actions">
                <div class="tooltip-demo">
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="View Task Details" class="btn btn-white btn-xs"><i class="fa fa-folder"></i> </a>
                </div>
            </td>
        </tr>
        <tr>
            <td class="project-status">
                <span class="label label-danger">Unassigned</span>
            </td>
            <td class="project-title">
                <strong>project referencereferencereference </strong>
                <br>
                <strong class="text-info">88888888-04</strong>  |  <code>English</code> <i class="fa fa-arrow-right"></i> <code>Japanese</code>
            </td>

            </td>
            <td class="project-title">
                <span class="text-danger"><strong>Un-Assigned</strong></span>
                <div class="tooltip-demo">
                    <code>Proofreading</code>  |  2014.Sep.08 -  2014.Oct.28
                </div>
            </td>
            <td class="project-actions">
                <div class="tooltip-demo">
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Send to Specialism Pool" class="btn btn-success btn-xs"><i class="fa fa-users"></i> S</a>
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Send to Client's Resource Pool" class="btn btn-info btn-xs"><i class="fa fa-users"></i> C</a>
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="View Task Details" class="btn btn-white btn-xs"><i class="fa fa-folder"></i> </a>
                    <a href="#" class="btn btn-white btn-xs"><i class="fa fa-trash-o"></i> </a>
                </div>
            </td>
        </tr>
        <tr>
            <td class="project-status">
                <span class="label label-warning">Pooling</span>
            </td>
            <td class="project-title">
                <strong>project referencereferencereference </strong>
                <br>
                <strong class="text-info">88888888-05</strong>  |  <code>English</code> <i class="fa fa-arrow-right"></i> <code>Japanese</code>
            </td>

            </td>
            <td class="project-title">
                <span class="text-warning"><strong>Assigned to Specialism Pool</strong></span>
                <div class="tooltip-demo">
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Desktop Publishing">DTP <i class="fa fa-apple"></i></code>  |  2014.Sep.08 -  2014.Oct.28
                </div>
            </td>
            <td class="project-actions">
                <div class="tooltip-demo">
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Send to Specialism Pool" class="btn btn-success btn-xs"><i class="fa fa-users"></i> S</a>
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Send to Client's Resource Pool" class="btn btn-info btn-xs"><i class="fa fa-users"></i> C</a>
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="View Task Details" class="btn btn-white btn-xs"><i class="fa fa-folder"></i> </a>
                    <a href="#" class="btn btn-white btn-xs"><i class="fa fa-trash-o"></i> </a>
                </div>
            </td>
        </tr>
        <tr>
            <td class="project-status">
                <span class="label label-info">Evaluating</span>
            </td>
            <td class="project-title">
                <strong>project referencereferencereference </strong>
                <br>
                <strong class="text-info">88888888-06</strong>  |  <code>English</code> <i class="fa fa-arrow-right"></i> <code>Japanese</code> <i class="fa fa-paperclip"></i> <!-- paperclip means freelancer uploaded the translated file -->
            </td>

            </td>
            <td class="project-title">
                <span class="text-warning"><strong>Assigned to Specialism Pool</strong></span>
                <div class="tooltip-demo">
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Engineering">ENG</code>  |  2014.Sep.08 -  2014.Oct.28
                </div>
            </td>
            <td class="project-actions">
                <div class="tooltip-demo">
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Send to Specialism Pool" class="btn btn-success btn-xs"><i class="fa fa-users"></i> S</a>
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Send to Client's Resource Pool" class="btn btn-info btn-xs"><i class="fa fa-users"></i> C</a>
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="View Task Details" class="btn btn-white btn-xs"><i class="fa fa-folder"></i> </a>
                    <a href="#" class="btn btn-white btn-xs"><i class="fa fa-trash-o"></i> </a>
                </div>
            </td>
        </tr>
        <tr>
            <td class="project-status">
                <span class="label label-warning">Pooling</span>
            </td>
            <td class="project-title">
                <strong>project referencereferencereference </strong>
                <br>
                <strong class="text-info">88888888-07</strong>  |  <code>English</code> <i class="fa fa-arrow-right"></i> <code>Japanese</code>
            </td>

            </td>
            <td class="project-title">
                <span class="text-warning"><strong>Assigned to Specialism Pool</strong></span>
                <div class="tooltip-demo">
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Consecutive Interpreting">Consecutive</code>  |  2014.Sep.08 -  2014.Oct.28
                </div>
            </td>
            <td class="project-actions">
                <div class="tooltip-demo">
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Send to Specialism Pool" class="btn btn-success btn-xs"><i class="fa fa-users"></i> S</a>
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Send to Client's Resource Pool" class="btn btn-info btn-xs"><i class="fa fa-users"></i> C</a>
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="View Task Details" class="btn btn-white btn-xs"><i class="fa fa-folder"></i> </a>
                    <a href="#" class="btn btn-white btn-xs"><i class="fa fa-trash-o"></i> </a>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</div>

</div>
<div class="tab-pane" id="message">
    <div class="feed-activity-list">
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Yang, Michael</strong> create quote. <br>
                <div class="well">
                    Project log or Description, if no log or description, then dont show div class=well
                </div>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 15:36</small>
                <strong>Smith, Alex</strong> accept the quote. <br>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong><a href="#" class="text-navy">freelancer_name1</a></strong> pick up task <a href="#" class="text-navy">#8888888-01</a>. <br>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong><a href="#" class="text-navy">freelancer_name2</a></strong> pick up task <a href="#" class="text-navy">#8888888-02</a>. <br>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong><a href="#" class="text-navy">freelancer_name2</a></strong> post message. <br>
                <div class="well">
                    Project log or Description, if no log or description, then dont show div class=well
                </div>
            </div>
        </div>

        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Yang, Michael</strong> create task <a href="#" class="text-navy">#8888888-03</a>. <br>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Smith, Alex</strong> post message. <br>
                <div class="well">
                    requirements
                </div>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Yang, Michael</strong> post message. <br>
                <div class="well">
                    answer
                </div>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Yang, Michael</strong> post message. <br>
                <div class="well">
                    answer
                </div>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Smith, Alex</strong> request re-do the project, project rejected. <br>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Smith, Alex</strong> accept the delivery, project closed. <br>
            </div>
        </div>
    </div>

    <br>
    <div class="form-group">
        <div class="summernote">

        </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group" align="right">
        <div class="col-sm-12">
            <button class="btn btn-primary" type="submit">Send</button>
        </div>
    </div>
</div>

<div class="tab-pane" id="files">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>Source File Name</th>
            <th>Size</th>
            <th>Time Stamp</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td><a href=""><i class="fa fa-file"></i> Project_document_SC.docx <i class="fa fa-cloud-download"></i></a> </td>
            <td>46.88 KB</td>
            <td>2014-Oct-09 16:30</td>
            <td><i class="fa fa-trash"></i></td>
        </tr>
        </tbody>
    </table>
    <div class="text-right m-t-md">
        <a href="#" class="btn btn-xs btn-primary"><i class="fa fa-cloud-upload"></i> Upload Source files</a>
    </div>
    <div class="hr-line-dashed"></div>
    <h4>Files For Client Review</h4>
    <div class="panel-body">
        <div class="panel-group" id="accordion_files">
            <div class="panel panel-default">
                <div class="panel-heading" style="padding-bottom: 10px;">
                    <h5 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion_files" href="#lang1_files"><i class="fa fa-exclamation-triangle text-danger"></i> English <i class="fa fa-arrow-right"></i> Simplify Chinese <i class="fa fa-paperclip"></i></a> <!-- with paperclip means file for this language has been uploaded -->
                    </h5>
                </div>
                <div id="lang1_files" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Languages</th>
                                <th>File Name</th>
                                <th>Size</th>
                                <th>Time Stamp</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>1</td>
                                <td>English <i class="fa fa-arrow-right"></i> Simplify Chinese</td>
                                <td><a href=""><i class="fa fa-file"></i> Project_document_SC.docx <i class="fa fa-cloud-download"></i></a> </td>
                                <td>46.88 KB</td>
                                <td>2014-Oct-09 16:30</td>
                                <td><i class="fa fa-trash"></i></td>
                            </tr>
                            </tbody>
                        </table>
                        <div class="text-center m-t-md">
                            <a href="#" class="btn btn-sm btn-primary"><i class="fa fa-cloud-upload"></i> Upload files</a>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="panel-body">
                            <div class="form-group">
                                <label class="control-label">What's wrong with the translation?</label>
                                <div class="checkbox"><label> <input type="checkbox" checked disabled value=""> It is incomplete </label></div>
                                <div class="checkbox"><label> <input type="checkbox" checked disabled value=""> It contains spelling or grammatical errors </label></div>
                                <div class="checkbox"><label> <input type="checkbox" disabled value=""> It misses key meaning or details from the original </label></div>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Comments</label>
                                <p>sdasdkjasdkas;dasdasjdlksjdlskdjasldj</p>
                            </div><!-- /form-group -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" style="padding-bottom: 10px;">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion_files" href="#lang2_files">English <i class="fa fa-arrow-right"></i> Traditional Chinese</a>
                    </h4>
                </div>
                <div id="lang2_files" class="panel-collapse collapse">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Languages</th>
                                <th>File Name</th>
                                <th>Size</th>
                                <th>Time Stamp</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>1</td>
                                <td>English <i class="fa fa-arrow-right"></i> Simplify Chinese</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td><i class="fa fa-trash"></i></td>
                            </tr>
                            </tbody>
                        </table>
                        <div class="text-center m-t-md">
                            <a href="#" class="btn btn-sm btn-primary"><i class="fa fa-cloud-upload"></i> Upload files</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" style="padding-bottom: 10px;">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion_files" href="#lang3_files">English <i class="fa fa-arrow-right"></i> German <i class="fa fa-paperclip"></i></a></a>
                    </h4>
                </div>
                <div id="lang3_files" class="panel-collapse collapse">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Languages</th>
                                <th>File Name</th>
                                <th>Size</th>
                                <th>Time Stamp</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>1</td>
                                <td>English <i class="fa fa-arrow-right"></i> German</td>
                                <td><a href=""><i class="fa fa-file"></i> Project_document_JP.docx <i class="fa fa-cloud-download"></i></a> </td>
                                <td>46.88 KB</td>
                                <td>2014-Oct-09 16:30</td>
                                <td></td>
                            </tr>
                            </tbody>
                        </table>
                        <div class="text-center m-t-md">
                            <a href="#" class="btn btn-sm btn-primary"><i class="fa fa-cloud-upload"></i> Upload files</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="tab-pane" id="feedback">
    <div class="panel-body">
        <div class="panel-group" id="accordion_feedback">
            <div class="panel panel-default">
                <div class="panel-heading" style="padding-bottom: 10px;">
                    <h5 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion_feedback" href="#feedback_lang1"><i class="fa fa-exclamation-triangle text-danger"></i> English <i class="fa fa-arrow-right"></i> Simplify Chinese </a>
                    </h5>
                </div>
                <div id="feedback_lang1" class="panel-collapse collapse in">
                    <br>
                    <div class="row form-horizontal">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Quality: </label>
                                <div class="col-lg-6"><p class="form-control-static"><span class="label label-primary">Satisfactory</span></p></div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Turn Around Time</label>
                                <div class="col-lg-8"><p class="form-control-static"><span class="label label-primary">Faster</span></p></div>
                            </div>
                        </div>
                    </div>

                    <div class="panel-body">
                        <div class="form-group">
                            <label class="control-label">Feed back to Translator and Project Manager</label>
                            <p>dfadlkfjadfjad;fjadsfjlfksdlf;sf;</p>
                        </div><!-- /form-group -->
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" style="padding-bottom: 10px;">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion_feedback" href="#feedback_lang2">English <i class="fa fa-arrow-right"></i> Traditional Chinese</a>
                    </h4>
                </div>
                <div id="feedback_lang2" class="panel-collapse collapse">
                    <br>
                    <div class="row form-horizontal">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Quality: </label>
                                <div class="col-lg-6"><p class="form-control-static"><span class="label label-primary">Satisfactory</span></p></div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Turn Around Time</label>
                                <div class="col-lg-8"><p class="form-control-static"><span class="label label-primary">Faster</span></p></div>
                            </div>
                        </div>
                    </div>

                    <div class="panel-body">
                        <div class="form-group">
                            <label class="control-label">Feed back to Translator and Project Manager</label>
                            <p>dfadlkfjadfjad;fjadsfjlfksdlf;sf;</p>
                        </div><!-- /form-group -->
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" style="padding-bottom: 10px;">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion_feedback" href="#feedback_lang3">English <i class="fa fa-arrow-right"></i> German </a>
                    </h4>
                </div>
                <div id="feedback_lang3" class="panel-collapse collapse">
                    <br>
                    <div class="row form-horizontal">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Quality: </label>
                                <div class="col-lg-6"><p class="form-control-static"><span class="label label-primary">Satisfactory</span></p></div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Turn Around Time</label>
                                <div class="col-lg-8"><p class="form-control-static"><span class="label label-primary">Faster</span></p></div>
                            </div>
                        </div>
                    </div>

                    <div class="panel-body">
                        <div class="form-group">
                            <label class="control-label">Feed back to Translator and Project Manager</label>
                            <p>dfadlkfjadfjad;fjadsfjlfksdlf;sf;</p>
                        </div><!-- /form-group -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- if the project status is quoted or quoting, then hide other tabs only show quote tab -->
<div class="tab-pane" id="quote">
<div class="row">
<div class="row">
    <div class="col-lg-12" align="right">
        <a href="#" class="btn btn-white"><i class="fa fa-pencil"></i> Edit </a>
        <a href="#" class="btn btn-white"><i class="fa fa-file-pdf-o "></i> Download </a>
        <a href="quote_print.html" target="_blank" class="btn btn-primary"><i class="fa fa-print"></i> Print Quote </a>
    </div>
</div>
<div class="hr-line-dashed"></div>
<div class="row">
    <div class="col-sm-6">
        <h4>Quote No.</h4>
        <h4 class="text-navy">QUO-000567F7-00</h4>

        <h5>From:</h5>
        <strong>Jiang, Kevin</strong><br>
        <strong>Project Manager</strong><br>
        <address>
            <strong>PaperTask Ltd.</strong><br>
            106 Jorg Avenu, 600/10<br>
            Chicago, VT 32456<br>
            <abbr title="Phone">P:</abbr> (0086) 10-85916568
        </address>
    </div>

    <div class="col-sm-6 text-right">
        <p>
            <span><strong>Quote Date:</strong> Marh 18, 2014</span><br/>
            <span><strong>Due Date:</strong> April 17, 2014</span>
        </p>
        <h5>To:</span></h5>
        <strong>Doe, John</strong><br>
        <strong>Marketing Manager</strong><br>
        <address>
            <strong>Corporate, Inc.</strong><br>
            112 Street Avenu, 1080<br>
            Miami, CT 445611<br>
            <abbr title="Phone">P:</abbr> (120) 9000-4321
        </address>

    </div>
</div>
<div class="hr-line-dashed"></div>
<h4>Dear John,</h4><br>
<h4>RE: project reference/file name</h4><br>
<p>Further to receipt of your enquiry, I now have pleasure in providing you with the cost for the above requirement.</p>
<p><strong>Service Level: <span class="text-navy">Business</span></strong></p>
<p><strong>Approximate duration: <span class="text-navy">3 Working days</span></strong></p>
<div class="hr-line-dashed"></div>
<div class="table-responsive m-t">
    <table class="table table-bordered invoice-table">
        <thead>
        <tr>
            <th>English to Chinese - Tasks</th>
            <th>Unit</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total Price</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><div><a data-toggle="collapse" href="#use_tm1"><i class="fa fa-eye"></i> <strong>uploaded file name 1 / or Task Name</strong></a> - <span class="text-navy"> Translation (Use TM)</span></div></td>
            <td>Word</td>
            <td>CNY 0.120</td>
            <td>1000</td>
            <td>CNY 120.00</td>
        </tr>
        <tr> <!-- this is only for translation use TM -->
            <td colspan="5">
                <div id="use_tm1" class="panel-collapse collapse">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>TM Template</th>
                                <th>Rate (%)</th>
                                <th>Unit Price</th>
                                <th>Quantity (Word)</th>
                                <th>Quantity</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Repetitions</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>100</td>
                                <td>CNY 1.20</td>
                            </tr>
                            <tr>
                                <td>100%</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>200</td>
                                <td>CNY 2.40</td>
                            </tr>
                            <tr>
                                <td>95%-99%</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>200</td>
                                <td>CNY 2.40</td>
                            </tr>
                            <tr>
                                <td>85%-94%</td>
                                <td>50%</td>
                                <td>CNY 0.06</td>
                                <td>300</td>
                                <td>CNY 18.00</td>
                            </tr>
                            <tr>
                                <td>75%-84%</td>
                                <td>50%</td>
                                <td>CNY 0.06</td>
                                <td>200</td>
                                <td>CNY 12.00</td>
                            </tr>
                            <tr>
                                <td>50%-74%</td>
                                <td>100%</td>
                                <td>CNY 0.12</td>
                                <td>1000</td>
                                <td>CNY 120.00</td>
                            </tr>
                            <tr>
                                <td>No Match</td>
                                <td>100%</td>
                                <td>CNY 0.12</td>
                                <td>1000</td>
                                <td>CNY 120.00</td>
                            </tr>
                            <tr>
                                <td colspan="4" align="right"><strong>Total</strong></td>
                                <td class="text-info">CNY xxxx.xx</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td><div><strong>uploaded file name 2 / or Task Name</strong> - <span class="text-navy"> Translation (No TM)</span></div></td>
            <td>Word</td>
            <td>CNY 0.12</td>
            <td>2000</td>
            <td>CNY 240.00</td>
        </tr>
        <tr>
            <td><div><strong>uploaded file name 1 / or Task Name</strong> - <span class="text-info">DTP <i class="fa fa-apple"></i></span></div></td>
            <td>Page</td>
            <td>CNY 10.00</td>
            <td>20</td>
            <td>CNY 200.00</td>
        </tr>
        </tbody>
    </table>
</div><!-- /table-responsive -->
<div class="table-responsive m-t">
    <table class="table table-bordered invoice-table">
        <thead>
        <tr>
            <th>English to Japanese - Tasks</th>
            <th>Unit</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total Price</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><div><a data-toggle="collapse" href="#use_tm2"><i class="fa fa-eye"></i> <strong>uploaded file name 1 / or Task Name</strong></a> - <span class="text-navy"> Translation (Use TM)</span></div></td>
            <td>Word</td>
            <td>CNY 0.120</td>
            <td>1000</td>
            <td>CNY 120.00</td>
        </tr>
        <tr> <!-- this is only for translation use TM -->
            <td colspan="5">
                <div id="use_tm2" class="panel-collapse collapse">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>TM Template</th>
                                <th>Rate (%)</th>
                                <th>Unit Price</th>
                                <th>Quantity (Word)</th>
                                <th>Quantity</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Repetitions</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>100</td>
                                <td>CNY 1.20</td>
                            </tr>
                            <tr>
                                <td>100%</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>200</td>
                                <td>CNY 2.40</td>
                            </tr>
                            <tr>
                                <td>95%-99%</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>200</td>
                                <td>CNY 2.40</td>
                            </tr>
                            <tr>
                                <td>85%-94%</td>
                                <td>50%</td>
                                <td>CNY 0.06</td>
                                <td>300</td>
                                <td>CNY 18.00</td>
                            </tr>
                            <tr>
                                <td>75%-84%</td>
                                <td>50%</td>
                                <td>CNY 0.06</td>
                                <td>200</td>
                                <td>CNY 12.00</td>
                            </tr>
                            <tr>
                                <td>50%-74%</td>
                                <td>100%</td>
                                <td>CNY 0.12</td>
                                <td>1000</td>
                                <td>CNY 120.00</td>
                            </tr>
                            <tr>
                                <td>No Match</td>
                                <td>100%</td>
                                <td>CNY 0.12</td>
                                <td>1000</td>
                                <td>CNY 120.00</td>
                            </tr>
                            <tr>
                                <td colspan="4" align="right"><strong>Total</strong></td>
                                <td class="text-info">CNY xxxx.xx</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td><div><strong>uploaded file name 2 / or Task Name</strong> - <span class="text-navy"> Translation (No TM)</span></div></td>
            <td>Word</td>
            <td>CNY 0.12</td>
            <td>2000</td>
            <td>CNY 240.00</td>
        </tr>
        <tr>
            <td><div><strong>uploaded file name 1 / or Task Name</strong> - <span class="text-info">DTP <i class="fa fa-windows"></i></span></div></td>
            <td>Page</td>
            <td>CNY 10.00</td>
            <td>20</td>
            <td>CNY 200.00</td>
        </tr>
        </tbody>
    </table>
</div><!-- /table-responsive -->
<table class="table invoice-total">
    <tbody>
    <tr>
        <td><strong>Sub Total :</strong></td>
        <td>CNY 1026.00</td>
    </tr>
    <tr>
        <td><strong>(-) Discount :</strong></td>
        <td><span class="text-danger"><strong>-</strong></span> CNY 100.00</td>
    </tr>
    <tr>
        <td><strong>TAX (6%):</strong></td>
        <td>CNY 235.98</td>
    </tr>
    <tr>
        <td><strong>TOTAL :</strong></td>
        <td>CNY 1261.98</td>
    </tr>
    </tbody>
</table>
<!-- if the client is uncontracted, then "make a payment" will show, if client type is "contracted", then dont show "make a payment" instead of "accept the quote" after accept, the project status changed from quoted to ordered -->
<div class="text-right">
    <button class="btn btn-primary"><i class="fa fa-dollar"></i> Quote Accepted</button>
</div>
<div class="hr-line-dashed"></div>
<div class="m-t">
    The above costs include supplying the translations as electronic files in formats per your requirements.
    <br><br>
    Should any amendments or changes to the source text be required after the project has commenced, they will be incorporated at the standard rate which can be provided upon request.
    <br><br>
    <strong>Turnaround Time</strong>
    <br>
    It would take approximately <span class="text-navy">3 working days</span> from your accept the quote order to complete the translation work.
    <br><br>
    We strongly recommend that any text be reviewed prior to going to print. We would be happy to liase with any reviewers in country should you require it.
    <br><br>
    <strong>Terms of Service</strong>
    <br>
    Work will be invoiced on completion of each stage of the client order. The Company cannot accept a delay in payment due to translated documents awaiting approval of agents abroad, unless by prior agreement at the commencement of the project.
    <br><br>
    Prices quoted are valid for 30 days after this letter.
    <br><br>
    If you should require any further information please do not hesitate to contact me.
    <br><br>
    Assuring you of our best attention at all times.
    <br><br>
    Yours sincerely,
    <br><br>
    Michael Yang<br>
    Project Manager/Sales Manager<br>
    <strong>PaperTask</strong>
</div>
</div>
</div>

<div class="tab-pane" id="invoice">
<div class="row">
<div class="row">
    <div class="col-lg-6">
        <form class="form-horizontal">
            <div class="form-group" id="inv_data">
                <label class="col-sm-3 control-label">Invoice Date *</label>

                <div class="col-sm-6 input-group date">
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" class="form-control" value="03/04/2014">
                                                                    <span class="input-group-btn">
                                                                        <button type="button" class="btn btn-primary">Set</button>
                                                                    </span>
                </div>

            </div>
    </div>
    <div class="col-lg-6" align="right">
        <a href="#" class="btn btn-white"><i class="fa fa-file-pdf-o "></i> Download </a>
        <a href="invoice_print.html" target="_blank" class="btn btn-primary"><i class="fa fa-print"></i> Print Invoice </a>
    </div>
</div>
<div class="hr-line-dashed"></div>
<div class="row">
    <div class="col-sm-6">
        <h4>Invoice No.</h4>
        <h4 class="text-navy">INV-000567F7-00</h4>

        <h5>From:</h5>
        <strong>Jiang, Kevin</strong><br>
        <strong>Project Manager</strong><br>
        <address>
            <strong>PaperTask Ltd.</strong><br>
            106 Jorg Avenu, 600/10<br>
            Chicago, VT 32456<br>
            <abbr title="Phone">P:</abbr> (0086) 10-85916568
        </address>
    </div>

    <div class="col-sm-6 text-right">
        <p>
            <span><strong>Invoice Date:</strong> Marh 18, 2014</span><br/>
            <span><strong>Due Date:</strong> April 17, 2014</span>
        </p>
        <h5>To:</span></h5>
        <strong>Doe, John</strong><br>
        <strong>Marketing Manager</strong><br>
        <address>
            <strong>Corporate, Inc.</strong><br>
            112 Street Avenu, 1080<br>
            Miami, CT 445611<br>
            <abbr title="Phone">P:</abbr> (120) 9000-4321
        </address>

    </div>
</div>

<div class="table-responsive m-t">
    <table class="table table-bordered invoice-table">
        <thead>
        <tr>
            <th>English to Chinese - Tasks</th>
            <th>Unit</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total Price</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><div><a data-toggle="collapse" href="#use_tm1"><i class="fa fa-eye"></i> <strong>uploaded file name 1 / or Task Name</strong></a> - <span class="text-navy"> Translation (Use TM)</span></div></td>
            <td>Word</td>
            <td>CNY 0.120</td>
            <td>1000</td>
            <td>CNY 120.00</td>
        </tr>
        <tr> <!-- this is only for translation use TM -->
            <td colspan="5">
                <div id="use_tm1" class="panel-collapse collapse">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>TM Template</th>
                                <th>Rate (%)</th>
                                <th>Unit Price</th>
                                <th>Quantity (Word)</th>
                                <th>Quantity</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Repetitions</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>100</td>
                                <td>CNY 1.20</td>
                            </tr>
                            <tr>
                                <td>100%</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>200</td>
                                <td>CNY 2.40</td>
                            </tr>
                            <tr>
                                <td>95%-99%</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>200</td>
                                <td>CNY 2.40</td>
                            </tr>
                            <tr>
                                <td>85%-94%</td>
                                <td>50%</td>
                                <td>CNY 0.06</td>
                                <td>300</td>
                                <td>CNY 18.00</td>
                            </tr>
                            <tr>
                                <td>75%-84%</td>
                                <td>50%</td>
                                <td>CNY 0.06</td>
                                <td>200</td>
                                <td>CNY 12.00</td>
                            </tr>
                            <tr>
                                <td>50%-74%</td>
                                <td>100%</td>
                                <td>CNY 0.12</td>
                                <td>1000</td>
                                <td>CNY 120.00</td>
                            </tr>
                            <tr>
                                <td>No Match</td>
                                <td>100%</td>
                                <td>CNY 0.12</td>
                                <td>1000</td>
                                <td>CNY 120.00</td>
                            </tr>
                            <tr>
                                <td colspan="4" align="right"><strong>Total</strong></td>
                                <td class="text-info">CNY xxxx.xx</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td><div><strong>uploaded file name 2 / or Task Name</strong> - <span class="text-navy"> Translation (No TM)</span></div></td>
            <td>Word</td>
            <td>CNY 0.12</td>
            <td>2000</td>
            <td>CNY 240.00</td>
        </tr>
        <tr>
            <td><div><strong>uploaded file name 1 / or Task Name</strong> - <span class="text-info">DTP <i class="fa fa-apple"></i></span></div></td>
            <td>Page</td>
            <td>CNY 10.00</td>
            <td>20</td>
            <td>CNY 200.00</td>
        </tr>
        </tbody>
    </table>
</div><!-- /table-responsive -->
<div class="table-responsive m-t">
    <table class="table table-bordered invoice-table">
        <thead>
        <tr>
            <th>English to Japanese - Tasks</th>
            <th>Unit</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total Price</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><div><a data-toggle="collapse" href="#use_tm2"><i class="fa fa-eye"></i> <strong>uploaded file name 1 / or Task Name</strong></a> - <span class="text-navy"> Translation (Use TM)</span></div></td>
            <td>Word</td>
            <td>CNY 0.120</td>
            <td>1000</td>
            <td>CNY 120.00</td>
        </tr>
        <tr> <!-- this is only for translation use TM -->
            <td colspan="5">
                <div id="use_tm2" class="panel-collapse collapse">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>TM Template</th>
                                <th>Rate (%)</th>
                                <th>Unit Price</th>
                                <th>Quantity (Word)</th>
                                <th>Quantity</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Repetitions</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>100</td>
                                <td>CNY 1.20</td>
                            </tr>
                            <tr>
                                <td>100%</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>200</td>
                                <td>CNY 2.40</td>
                            </tr>
                            <tr>
                                <td>95%-99%</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>200</td>
                                <td>CNY 2.40</td>
                            </tr>
                            <tr>
                                <td>85%-94%</td>
                                <td>50%</td>
                                <td>CNY 0.06</td>
                                <td>300</td>
                                <td>CNY 18.00</td>
                            </tr>
                            <tr>
                                <td>75%-84%</td>
                                <td>50%</td>
                                <td>CNY 0.06</td>
                                <td>200</td>
                                <td>CNY 12.00</td>
                            </tr>
                            <tr>
                                <td>50%-74%</td>
                                <td>100%</td>
                                <td>CNY 0.12</td>
                                <td>1000</td>
                                <td>CNY 120.00</td>
                            </tr>
                            <tr>
                                <td>No Match</td>
                                <td>100%</td>
                                <td>CNY 0.12</td>
                                <td>1000</td>
                                <td>CNY 120.00</td>
                            </tr>
                            <tr>
                                <td colspan="4" align="right"><strong>Total</strong></td>
                                <td class="text-info">CNY xxxx.xx</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td><div><strong>uploaded file name 2 / or Task Name</strong> - <span class="text-navy"> Translation (No TM)</span></div></td>
            <td>Word</td>
            <td>CNY 0.12</td>
            <td>2000</td>
            <td>CNY 240.00</td>
        </tr>
        <tr>
            <td><div><strong>uploaded file name 1 / or Task Name</strong> - <span class="text-info">DTP <i class="fa fa-windows"></i></span></div></td>
            <td>Page</td>
            <td>CNY 10.00</td>
            <td>20</td>
            <td>CNY 200.00</td>
        </tr>
        </tbody>
    </table>
</div><!-- /table-responsive -->
<table class="table invoice-total">
    <tbody>
    <tr>
        <td><strong>Sub Total :</strong></td>
        <td>CNY 1026.00</td>
    </tr>
    <tr>
        <td><strong>(-) Discount :</strong></td>
        <td><span class="text-danger"><strong>-</strong></span> CNY 100.00</td>
    </tr>
    <tr>
        <td><strong>TAX (6%):</strong></td>
        <td>CNY 235.98</td>
    </tr>
    <tr>
        <td><strong>TOTAL :</strong></td>
        <td>CNY 1261.98</td>
    </tr>
    </tbody>
</table>
<div class="hr-line-dashed"></div>
<div class="m-t">
    <h2 class="text-center text-danger">Due Date: October 23rd, 2014</h2>
    <br>
    <div class="row">
        <div class="col-lg-6">
            <dl class="dl-horizontal">
                <dt><h4>Bank Details</h4></dt><dd></dd>
                <dt>Company Name:</dt> <dd>AccessPath Limited</dd>
                <dt>Bank Name:</dt> <dd>HSBC Hong Kong</dd>
                <dt>Bank Address:</dt> <dd>Shops 110-120, 1/F Emperor Group Centre, 288 Hennessy Road, Wanchai, Hong Kong</dd>
                <dt>Account Number:</dt> <dd>640 037941 838</dd>
                <dt>Swift Code:</dt> <dd>HSBCHKHHHKH</dd>
            </dl>
        </div>
        <div class="col-lg-6">
            <dl class="dl-horizontal">
                <dt><h4>Other Payment Methods</h4></dt><dd></dd>
                <dt>Paypal:</dt> <dd>payments@papertask.com</dd>
                <dt>Alipay:</dt> <dd>payments@papertask.com</dd>
            </dl>
        </div>
    </div>
    <br><br>
    <h2 class="text-center"><em>Thank you for your business!</em></h2>
</div>
</div>
</div>

</div>

</div>

</div>
</div>
</div>
</div>
</div>
</div>
</div>