<div class="wrapper wrapper-content animated fadeInUp">

<div class="ibox">
<div class="ibox-title">
    <h5> Projects List</h5>
    <div class="ibox-tools">
        <a href="" class="btn btn-primary btn-xs">Create new project</a>
    </div>
</div>
<div class="ibox-content">
<div class="row m-b-sm m-t-sm">
    <div class="col-md-1">
        <button type="button" id="loading-example-btn" class="btn btn-white btn-sm" ><i class="fa fa-refresh"></i> Refresh</button>
    </div>
    <div class="col-md-9">
        <div class="input-group">
            <input type="text" placeholder="Search" class="input-sm form-control">
                                    	<span class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary"> Search</button>
                                      </span>
        </div>
    </div>
    <div class="col-md-2">
        <a data-toggle="collapse" href="#adv_search" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Advance Search</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div id="adv_search" class="panel-collapse collapse faq-answer">
            <form method="" class="form-horizontal">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> ID</label>
                            <div class="col-sm-9"><input type="text" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Source</label>
                            <div class="col-sm-9">
                                <select class="form-control" name="">
                                    <option></option>
                                    <option value="">Admin</option>
                                    <option value="">General Manager</option>
                                    <option value=""></option>
                                    <option value="">Financial Manager</option>
                                    <option value=""></option>
                                    <option value="">Sales Director</option>
                                    <option value="">Sales</option>
                                    <option value=""></option>
                                    <option value="">Operation Manager</option>
                                    <option value="">Project Manager</option>
                                    <option value="">In-house Translator</option>
                                    <option value="">In-house Editor/Proofreader</option>
                                    <option value="">In-house DTP</option>
                                    <option value="">In-house Engineering</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Order</label>
                            <div class="col-sm-9">
                                <div class="input-group date">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    <input type="text" class="form-control" value="">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Client ID</label>
                            <div class="col-sm-9"><input type="text" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">PM</label>
                            <div class="col-sm-9">
                                <select class="form-control" name="">
                                    <option></option>
                                    <option value="">Admin</option>
                                    <option value="">General Manager</option>
                                    <option value=""></option>
                                    <option value="">Financial Manager</option>
                                    <option value=""></option>
                                    <option value="">Sales Director</option>
                                    <option value="">Sales</option>
                                    <option value=""></option>
                                    <option value="">Operation Manager</option>
                                    <option value="">Project Manager</option>
                                    <option value="">In-house Translator</option>
                                    <option value="">In-house Editor/Proofreader</option>
                                    <option value="">In-house DTP</option>
                                    <option value="">In-house Engineering</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Reference</label>
                            <div class="col-sm-9"><input type="text" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Target</label>
                            <div class="col-sm-9">
                                <select class="form-control" name="">
                                    <option></option>
                                    <option value="">Admin</option>
                                    <option value="">General Manager</option>
                                    <option value=""></option>
                                    <option value="">Financial Manager</option>
                                    <option value=""></option>
                                    <option value="">Sales Director</option>
                                    <option value="">Sales</option>
                                    <option value=""></option>
                                    <option value="">Operation Manager</option>
                                    <option value="">Project Manager</option>
                                    <option value="">In-house Translator</option>
                                    <option value="">In-house Editor/Proofreader</option>
                                    <option value="">In-house DTP</option>
                                    <option value="">In-house Engineering</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Completed</label>
                            <div class="col-sm-9">
                                <div class="input-group date">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    <input type="text" class="form-control" value="">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Company</label>
                            <div class="col-sm-9"><input type="text" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Sales</label>
                            <div class="col-sm-9">
                                <select class="form-control" name="">
                                    <option></option>
                                    <option value="">Admin</option>
                                    <option value="">General Manager</option>
                                    <option value=""></option>
                                    <option value="">Financial Manager</option>
                                    <option value=""></option>
                                    <option value="">Sales Director</option>
                                    <option value="">Sales</option>
                                    <option value=""></option>
                                    <option value="">Operation Manager</option>
                                    <option value="">Project Manager</option>
                                    <option value="">In-house Translator</option>
                                    <option value="">In-house Editor/Proofreader</option>
                                    <option value="">In-house DTP</option>
                                    <option value="">In-house Engineering</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Field</label>
                            <div class="col-sm-9">
                                <select class="form-control" name="">
                                    <option></option>
                                    <option value="">Admin</option>
                                    <option value="">General Manager</option>
                                    <option value=""></option>
                                    <option value="">Financial Manager</option>
                                    <option value=""></option>
                                    <option value="">Sales Director</option>
                                    <option value="">Sales</option>
                                    <option value=""></option>
                                    <option value="">Operation Manager</option>
                                    <option value="">Project Manager</option>
                                    <option value="">In-house Translator</option>
                                    <option value="">In-house Editor/Proofreader</option>
                                    <option value="">In-house DTP</option>
                                    <option value="">In-house Engineering</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Status</label>
                            <div class="col-sm-9">
                                <select class="form-control" name="">
                                    <option></option>
                                    <option value="">Ordered</option>
                                    <option value="">Ongoing</option>
                                    <option value="">Reviewing</option>
                                    <option value="">Completed</option>
                                    <option value="">Rejected</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Pay Status</label>
                            <div class="col-sm-9">
                                <select class="form-control" name="">
                                    <option></option>
                                    <option value="">Paid</option>
                                    <option value="">Unpaid</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-right tooltip-demo">
                    <a href="#" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Search</a>
                    <a href="#" class="btn btn-white btn-sm" type="reset"><i class="fa fa-times"></i> Reset</a>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="hr-line-dashed"></div>

<div class="project-list">

    <table class="table table-hover">
        <tbody>
        <tr>
            <td class="project-status">
                <span class="label label-warning">8</span> <span class="label label-danger">Ordered</span>
            </td>
            <td class="project-status">
                <span class="btn btn-outline btn-info btn-sm">Business</span>
            </td>
            <td class="project-title">
                <strong>Contract with Zender Company</strong>
                <br/>
                <div class="tooltip-demo">
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation with Translation Memory">TM</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation without Translation Memory">No-TM</code>
                    <code>Proofreading</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Desktop Publishing">DTP</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Engineering">ENG</code>
                </div>
            </td>
            <td class="project-title">
                <span class="">88888888</span>
                <br/>
                <small>2014.Sep.09 - 2014.Oct.18</small>
            </td>
            <td class="project-title">
                Client's name
                <br/>
                Client's Company
            </td>
            <td class="project-actions">
                <a href="#" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> </a>
                <a href="#" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> </a>
                <a href="#" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> </a> <!-- only admin has right to show the delete button -->
            </td>
        </tr>
        <tr>
            <td class="project-status">
                <!-- this is messages/activity --><span class="label label-warning">2</span> <span class="label label-primary">Ongoing</span>
            </td>
            <td class="project-status">
                <span class="btn btn-outline btn-success btn-sm">Professional</span>
            </td>
            <td class="project-title">
                <strong>Contract with Zender Company</strong>
                <br/>
                <div class="tooltip-demo">
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation with Translation Memory">TM</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation without Translation Memory">No-TM</code>
                    <code>Proofreading</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Desktop Publishing">DTP</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Engineering">ENG</code>
                </div>
            </td>
            <td class="project-title">
                <span class="">88888888</span>
                <br/>
                <small>2014.Sep.09 - 2014.Oct.18</small>
            </td>
            <td class="project-title">
                Client's name
                <br/>
                Client's Company
            </td>
            <td class="project-actions">
                <a href="#" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> </a>
                <a href="#" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> </a>
                <a href="#" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> </a> <!-- only admin has right to show the delete button -->
            </td>
        </tr>
        <tr>
            <td class="project-status">
                <span class="label label-success">Reviewing</span>
            </td>
            <td class="project-status">
                <span class="btn btn-outline btn-primary btn-sm">Premium</span>
            </td>
            <td class="project-title">
                <strong>Contract with Zender Company</strong>
                <br/>
                <div class="tooltip-demo">
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation with Translation Memory">TM</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation without Translation Memory">No-TM</code>
                    <code>Proofreading</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Desktop Publishing">DTP</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Engineering">ENG</code>
                </div>
            </td>
            <td class="project-title">
                <span class="">88888888</span>
                <br/>
                <small>2014.Sep.09 - 2014.Oct.18</small>
            </td>
            <td class="project-title">
                Client's name
                <br/>
                Client's Company
            </td>
            <td class="project-actions">
                <a href="#" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> </a>
                <a href="#" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> </a>
                <a href="#" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> </a> <!-- only admin has right to show the delete button -->
            </td>
        </tr>
        <tr>
            <td class="project-status">
                <span class="label label-default">Completed</span> <i class="fa fa-usd"></i> <!--with dollor sign means paid -->
            </td>
            <td class="project-status">
                <span class="btn btn-outline btn-primary btn-sm">Premium</span>
            </td>
            <td class="project-title">
                <strong>Contract with Zender Company</strong>
                <br/>
                <div class="tooltip-demo">
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation with Translation Memory">TM</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation without Translation Memory">No-TM</code>
                    <code>Proofreading</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Desktop Publishing">DTP</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Engineering">ENG</code>
                </div>
            </td>
            <td class="project-title">
                <span class="">88888888</span>
                <br/>
                <small>2014.Sep.09 - 2014.Oct.18</small>
            </td>
            <td class="project-title">
                Client's name
                <br/>
                Client's Company
            </td>
            <td class="project-actions">
                <a href="#" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> </a>
                <a href="#" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> </a>
                <a href="#" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> </a> <!-- only admin has right to show the delete button -->
            </td>
        </tr>
        <tr>
            <td class="project-status">
                <span class="label label-white">Rejected</span>
            </td>
            <td class="project-status">
                <span class="btn btn-outline btn-primary btn-sm">Premium</span>
            </td>
            <td class="project-title">
                <strong>Contract with Zender Company</strong>
                <br/>
                <div class="tooltip-demo">
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation with Translation Memory">TM</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation without Translation Memory">No-TM</code>
                    <code>Proofreading</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Desktop Publishing">DTP</code>
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Engineering">ENG</code>
                </div>
            </td>
            <td class="project-title">
                <span class="">88888888</span>
                <br/>
                <small>2014.Sep.09 - 2014.Oct.18</small>
            </td>
            <td class="project-title">
                Client's name
                <br/>
                Client's Company
            </td>
            <td class="project-actions">
                <a href="#" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> </a>
                <a href="#" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> </a>
                <a href="#" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> </a> <!-- only admin has right to show the delete button -->
            </td>
        </tr>
        </tbody>
    </table>
</div>

<div class="btn-group text-right">
    <button type="button" class="btn btn-white"><i class="fa fa-chevron-left"></i></button>
    <button class="btn btn-white">1</button>
    <button class="btn btn-white  active">2</button>
    <button class="btn btn-white">3</button>
    <button class="btn btn-white">4</button>
    <button type="button" class="btn btn-white"><i class="fa fa-chevron-right"></i> </button>
</div>
</div>
</div>
</div>