<?php $this->headTitle($this->translate('Project detail')) ?>
<!-- Le styles -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.js')
    ->prependFile($this->basePath() . '/js/admin/project/project-index.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload']);")
    ->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
    //->prependFile($this->basePath() . '/js/plugins/datapicker/bootstrap-datepicker.js')
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js')
?>
<div class="row">
<div class="col-lg-12">
<div class="wrapper wrapper-content animate fadeInUp">

<div class="ibox">
<div class="ibox-title">
    <h5> Projects List</h5>
    <div class="ibox-tools">
        <a href="" class="btn btn-primary btn-xs">Create new project</a>
    </div>
</div>
<div class="ibox-content">
    <div class="row m-b-sm m-t-sm">
        <div class="col-md-1">
            <button type="button" id="loading-example-btn" class="btn btn-white btn-sm" ><i class="fa fa-refresh"></i> Refresh</button>
        </div>
        <div class="col-md-9">
            <div class="input-group">
                <input type="text" placeholder="Search" class="input-sm form-control">
                                            <span class="input-group-btn">
                                            <button type="button" class="btn btn-sm btn-primary"> Search</button>
                                          </span>
            </div>
        </div>
        <div class="col-md-2">
            <a data-toggle="collapse" href="#adv_search" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Advance Search</a>
        </div>
    </div>
    <div ng-controller="ProjectIndexController">
        <div class="row">
            <div class="col-lg-12">
                <div id="adv_search" class="panel-collapse collapse faq-answer">
                    <?php include "index/search.phtml" ?>
                </div>
            </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div ng-controller="ItemListController">
            <div class="project-list">
                <table class="table table-hover">
                    <tbody>
                    <tr ng-repeat="project in items">
                        <td class="project-status">
                            <span class="label label-warning" ng-if="project.number">{{ project.number }}</span>
                            <span class="label label-{{ ProjectStatus.get(project.status).decorator }}"
                                >{{ ProjectStatus.get(project.status).name }}</span>
                        </td>
                        <td class="project-status">
                            <span class="btn btn-outline btn-{{ ProjectServiceLevel.get(project.serviceLevel).decorator }}
                            btn-sm">{{ ProjectServiceLevel.get(project.serviceLevel).name }}</span>
                        </td>
                        <td class="project-title">
                            <strong><?php echo $this->translate('Contract with') ?> {{ project.client.company.name }}</strong>
                            <br/>
                            <div class="tooltip-demo">
                                <span ng-repeat="type in TypeList.getProjectTypes(project)">
                                    <code {{ TypeList.getTypeAttrs(type) }}>{{ TypeList.getDisplayName(type) }}</code>
                                </span>
                            </div>
                        </td>
                        <td class="project-title">
                            <span class="">{{ project.reference }}</span>
                            <br/>
                            <small>{{ DateFormatter.short(project.startDate) }} - {{ DateFormatter.short(project.dueDate) }}</small>
                        </td>
                        <td class="project-title">
                            {{ project.client.name }}
                            <br/>
                            {{ project.client.company.name }}
                        </td>
                        <td class="project-actions">
                            <a href="#" class="btn btn-white btn-sm"
                               ng-click="goToDetail(project)"><i class="fa fa-folder"></i> </a>
                            <a href="#" class="btn btn-white btn-sm"
                               ng-click="goToEdit(project)"><i class="fa fa-pencil"></i> </a>
                            <a href="#" class="btn btn-danger btn-sm"
                               ng-show="CurrentUser.is_admin()" ng-click="remove($index)"><i class="fa fa-trash"></i> </a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>

            <div class="btn-group text-right">
                <button type="button" class="btn btn-white"
                        ng-click="previous()" {{ prev_disabled }}><i class="fa fa-chevron-left"></i></button>
                <button class="btn btn-white {{ page.is_active }}"
                        ng-click="goTo(page)" ng-repeat="page in getPages()">{{ page.number }}</button>
                <button type="button" class="btn btn-white"
                        ng-click="next()" {{ next_disabled }}><i class="fa fa-chevron-right"></i> </button>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
</div>