<?php $this->headTitle($this->translate('Add New Project')) ?>
<!-- Le styles -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.js')
    ->prependFile($this->basePath() . '/js/admin/project/create-project.js')
    ->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', ['summernote']);")
    ->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
    //->prependFile($this->basePath() . '/js/plugins/datapicker/bootstrap-datepicker.js')
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js')
?>
<style>
    .form-group label.btn-outline {
        margin-right: 0.3em;
    }
    input[readonly][data-field=datetime]{
        background-color: #fff;
    }
    input[readonly][data-field=datetime]:hover,
    i.fa.fa-calendar:hover{
        cursor: pointer;
    }
</style>
<div class="row">
<div class="col-lg-12">
<div class="ibox">
<div class="ibox-title">
    <h5><i class="fa fa-archive"></i> Create Project</h5>
</div>
<div class="ibox-content">

<form id="form" action="#" class="wizard-big" ng-controller="CreateProjectController">
<h1>Project Information</h1>
<fieldset>
<button type="button" ng-click="test()">Test</button>
<div class="ibox">
    <div class="ibox-title" id="project-type">
        <h5><i class="fa fa-puzzle-piece"></i> Project Type & Status</h5>
        <input type="text" class="hidden-required required valid" ng-value="projectType()">
    </div>
    <div class="ibox-content">
        <div class="form-group project-types">
            <label class="col-sm-3 control-label">
                <h4><i class="fa fa-coffee"></i>&nbsp; Translation</h4>
            </label>
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-primary {{translation_active[translation.id]}}"
                       ng-repeat="translation in translations" ng-click="addTranslation(translation)">
                    <input type="checkbox" name="type" ng-value="translation.id"/> {{translation.name}}
                </label>
            </div>
        </div>
        <div class="form-group project-types">
            <label class="col-sm-3 control-label">
                <h4><i class="fa fa-desktop"></i> &nbsp;DTP/Engineering</h4>
            </label>
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-primary {{dtp_active[dtp.id]}}" ng-repeat="dtp in dtps"
                       ng-click="addDtp(dtp)">
                    <input type="checkbox" name="type" ng-value="dtp.id" /> <span ng-bind-html="dtp.name"></span>
                </label>
            </div>
        </div>
        <div class="form-group" id="project-interpreting">
            <label class="col-sm-3 control-label">
                <h4><i class="fa fa-comments-o"></i> &nbsp; Interpreting</h4>
            </label>
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-primary {{interpreting == project.interpreting ? 'active': ''}}"
                       ng-repeat="interpreting in interpretings" ng-click="setInterpreting(interpreting)">
                    <input type="radio" name="type" ng-value="intepreting.id" /> {{interpreting.name}}
                </label>
            </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group" style="margin-bottom: 0px;">
            <label class="col-sm-3 control-label">
                <h4><i class="fa fa-cube"></i> &nbsp;Status</h4>
            </label>
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-{{status.decorator}}" ng-repeat="status in statuses"
                       ng-click="project.status=status">
                    <input type="radio" name="status" ng-value="status.id" class="required valid"
                           data-errorplace="element.parent().parent().after(error)"/> {{status.name}}
                </label>
            </div>
        </div>
    </div>
</div>

<div class="ibox">
    <div class="ibox-title">
        <h5><i class="fa fa-files-o"></i> Project Files </h5>
        <div class="ibox-tools" id="files">
            <input type="file" name="files[]"/>
        </div>
    </div>
    <div class="ibox-content">
        <div class="row">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>File Name</th>
                    <th>File Size</th>
                    <th>Time Stamp</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="file in project.files">
                    <td>{{$index + 1}}</td>
                    <td><a href="#">{{file.name}}</a></td>
                    <td class="text-right">{{file.size}}</td>
                    <td>{{file.time}}</td>
                    <td class="text-center child-is-link">
                        <i ng-click="removeFile($index)" class="fa fa-trash-o text-danger"></i>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="ibox">
    <div class="ibox-title">
        <h5><i class="fa fa-list-ol"></i> Translation Languages</h5>
    </div>
    <div class="ibox-content">
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group form-horizontal">
                    <label class="col-sm-4 control-label">Source Language *</label>
                    <div class="col-sm-8">
                        <select class="form-control required valid" name="sourceLanguage" aria-required="true"
                                ng-options="language.name for language in languages"
                                ng-model="project.sourceLanguage">
                            <option value="">--</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="col-sm-5 control-label">Target Languages * &nbsp; </label>
                    <div class="col-sm-7">
                        <input type="text" class="hidden-required required valid" name="h1"
                               ng-value="project.targetLanguages.length > 0 ? '1' : ''">
                        <select class="form-control required valid multiselect" multiple="multiple" data-role="multiselect"
                                ng-options="language.name for language in languages"
                                ng-model="project.targetLanguages" ng-multiple="true">
                            <option value="">--</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="ibox">
    <div class="ibox-title">
        <h5><i class="fa fa-info-circle"></i> Project Information</h5>
    </div>
    <div class="ibox-content">
        <div class="row form-horizontal">
            <div class="row">
                <div class="col-lg-8">
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Reference *</label>
                        <div class="col-sm-9">
                            <input name="reference" ng-model="project.reference" type="text"
                                   aria-required="true" class="form-control required valid"/>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Priority *</label>
                        <div class="col-sm-8">
                            <div data-toggle="buttons">
                                <label class="btn btn-outline btn-{{priority.decorator}} btn-sm"
                                       ng-click="project.priority=priority" ng-repeat="priority in priorities">
                                    <input type="radio" name="priority" ng-value="priority"
                                           class="required valid"
                                           data-errorplace="element.parent().parent().before(error)" /> {{priority.name}}
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6">
                <div class="form-group" id="ordered_date">
                    <label class="col-sm-3 control-label">Start Date *</label>
                    <div class="col-sm-9">
                        <div class="input-group date">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            <input data-field="datetime" readonly type="text" name="startDate" ng-model="project.startDate"
                                   class="form-control required valid" data-errorplace="element.parent().before(error)"/>
                        </div>
                        <div class="dtbox"></div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">Field *</label>
                    <div class="col-sm-9">
                        <select class="form-control required valid" name="field" aria-required="true"
                                ng-model="project.field" ng-options="field.name for field in fields">
                            <option value="">--</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">Sales </label>
                    <div class="col-sm-9">
                        <select class="form-control" name="sale" aria-required="true"
                                ng-model="project.sale" ng-options="sale.name for sale in sales">
                            <option value="">--</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group" id="due_date">
                    <label class="col-sm-3 control-label">Due Date *</label>
                    <div class="col-sm-9">
                        <div class="input-group date">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            <input data-field="datetime" readonly type="text" name="dueDate" ng-model="project.dueDate"
                                   class="form-control required valid" data-errorplace="element.parent().before(error)"/>
                        </div>
                        <div class="dtbox"></div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">Client *</label>
                    <div class="col-sm-9">
                        <select class="form-control required valid" name="client" aria-required="true"
                                ng-model="project.client" ng-options="client.name for client in clients">
                            <option value="">--</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">PM *</label>
                    <div class="col-sm-9">
                        <select class="form-control required valid" name="pm" aria-required="true"
                                ng-model="project.pm" ng-options="pm.name for pm in pms">
                            <option value="">--</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div ng-show="project.interpreting">
            <div class="hr-line-dashed"></div>
            <div class="row">

                <div class="form-group">
                    <label class="col-sm-2 control-label">Interpreting Info </label>
                    <div class="col-sm-10">
                        <input name="interpretingInfo" type="text" class="form-control"
                               ng-model="project.interpretingInfo"/>
                        <span class="help-block m-b-none">Interpreting only, put address/city/country information.</span>
                    </div>
                </div>

            </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Project Description </label>
            <summernote ng-model="project.description"></summernote>
        </div>

    </div>
</div>

</fieldset>

<h1>Order Information</h1>
<fieldset>
<!-- here load the default service level for the client choosed previous step, if there is not price for the client,
then load PaperTask Price -->
<div class="ibox">
    <div class="ibox-title">
        <h4><i class="fa fa-sitemap"></i> Service Level <small>Project default service level</small></h4>
    </div>
    <div class="ibox-content wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-6">
                <div data-toggle="buttons">
                    <label class="btn btn-outline btn-primary" ng-repeat="level in levels"
                           ng-click="order.level=level">
                        <input type="radio" name="level" value="{{level.id}}" /> {{level.name}}
                    </label>
                </div>
            </div>
            <div class="col-lg-6 form-horizontal">
                <div class="form-group">
                    <label class="col-sm-6 control-label">Approximate duration *</label>
                    <div class="col-sm-3">
                        <input ng-model="order.duration" type="text" class="form-control" />
                    </div>
                    <span class="col-sm-3 control-label">Working days</span>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="ibox">
<div class="ibox-title">
    <h4><i class="fa fa-file-text-o"></i> Order/Quote Information</h4>
</div>
<div class="ibox-content wrapper wrapper-content">
<div class="panel blank-panel">

<div class="panel-heading">
    <div class="panel-title m-b-md"><h4>Source Language - {{project.sourceLanguage.name}}</h4></div>
    <div class="panel-options">

        <ul class="nav nav-tabs">
            <li ng-repeat="language in project.targetLanguages" class="{{$index == 0 ? 'active': ''}}">
                <a data-toggle="tab" href="#tab-{{language.id}}">{{language.name}}</a>
            </li>
        </ul>
    </div>
</div>

<div class="panel-body">

<div class="tab-content">
<div id="tab-{{language.id}}" class="tab-pane {{$index == 0 ? 'active': ''}}"
     ng-repeat="language in project.targetLanguages">
<div class="panel panel-default">
    <div class="panel-heading" style="padding-bottom: 10px;">
        Translation - <span class="text-info"><strong>Business</strong></span>
    </div>
    <div class="panel-body">

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms - <span class="text-info">Translation (No TM)</span></th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>uploaded file name 1 / or Task Name</td>
                    <td>Source Word</td>
                    <td>CNY 0.12</td>
                    <td>2000</td>
                    <td>CNY 240.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-translation-noTM"><i class="fa fa-edit"></i></a>
                        &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>uploaded file name 2 / or Task Name</td>
                    <td>Source Word</td>
                    <td>CNY 0.12</td>
                    <td>1000</td>
                    <td>CNY 120.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-translation-noTM"><i class="fa fa-edit"></i></a>
                        &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
        <div class="text-center">
            <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-translation-noTM">Add Iterm</a>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms - <span class="text-info">Translation (Use TM)</span></th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>2</td>
                    <td>Translation with TM</td>
                    <td>Source Word</td>
                    <td>CNY 0.12</td>
                    <td>1000</td>
                    <td>CNY 120.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-translation-TM"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;

                        <a data-toggle="collapse" href="#use_tm"><i class="fa fa-eye"></i></a>
                    </td>
                </tr>
                <tr>
                    <td colspan="7">
                        <div id="use_tm" class="panel-collapse collapse">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>TM Template</th>
                                        <th>Rate (%)</th>
                                        <th>Unit Price</th>
                                        <th>Quantity (Word)</th>
                                        <th>Quantity</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>Repetitions</td>
                                        <td>10%</td>
                                        <td>CNY 0.012</td>
                                        <td>100</td>
                                        <td>CNY 1.20</td>
                                    </tr>
                                    <tr>
                                        <td>100%</td>
                                        <td>10%</td>
                                        <td>CNY 0.012</td>
                                        <td>200</td>
                                        <td>CNY 2.40</td>
                                    </tr>
                                    <tr>
                                        <td>95%-99%</td>
                                        <td>10%</td>
                                        <td>CNY 0.012</td>
                                        <td>200</td>
                                        <td>CNY 2.40</td>
                                    </tr>
                                    <tr>
                                        <td>85%-94%</td>
                                        <td>50%</td>
                                        <td>CNY 0.06</td>
                                        <td>300</td>
                                        <td>CNY 18.00</td>
                                    </tr>
                                    <tr>
                                        <td>75%-84%</td>
                                        <td>50%</td>
                                        <td>CNY 0.06</td>
                                        <td>200</td>
                                        <td>CNY 12.00</td>
                                    </tr>
                                    <tr>
                                        <td>50%-74%</td>
                                        <td>100%</td>
                                        <td>CNY 0.12</td>
                                        <td>1000</td>
                                        <td>CNY 120.00</td>
                                    </tr>
                                    <tr>
                                        <td>No Match</td>
                                        <td>100%</td>
                                        <td>CNY 0.12</td>
                                        <td>1000</td>
                                        <td>CNY 120.00</td>
                                    </tr>
                                    <tr>
                                        <td colspan="4" align="right"><strong>Total</strong></td>
                                        <td class="text-info">CNY xxxx.xx</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading" style="padding-bottom: 10px;">
        Desktop Publishing
    </div>
    <div class="panel-body">

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms - <span class="text-info">DTP <i class="fa fa-apple"></i></span></th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>uploaded file name 1 / or Task Name</td>
                    <td>Page</td>
                    <td>CNY 10.00</td>
                    <td>10</td>
                    <td>CNY 100.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-dtp-mac"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>uploaded file name 2 / or Task Name</td>
                    <td>Source Word</td>
                    <td>CNY 50.00</td>
                    <td>2</td>
                    <td>CNY 100.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-dtp-mac"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
        <div class="text-center">
            <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-dtp-mac">Add Iterm</a>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms - <span class="text-info">DTP <i class="fa fa-windows"></i></span></th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>uploaded file name 1 / or Task Name</td>
                    <td>Page</td>
                    <td>CNY 10.00</td>
                    <td>10</td>
                    <td>CNY 100.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-dtp-pc"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>uploaded file name 2 / or Task Name</td>
                    <td>Hour</td>
                    <td>CNY 50.00</td>
                    <td>5</td>
                    <td>CNY 250.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-dtp-pc"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
        <div class="text-center">
            <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-dtp-pc">Add Iterm</a>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading" style="padding-bottom: 10px;">
        Engineering
    </div>
    <div class="panel-body">

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms</th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>uploaded file name 1 / or Task Name</td>
                    <td>Graphic</td>
                    <td>CNY 10.00</td>
                    <td>10</td>
                    <td>CNY 100.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-eng"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>uploaded file name 2 / or Task Name</td>
                    <td>Hour</td>
                    <td>CNY 50.00</td>
                    <td>2</td>
                    <td>CNY 100.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-eng"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
        <div class="text-center">
            <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-eng">Add Iterm</a>
        </div>
    </div>
</div>

<div class="panel panel-default" ng-show="project.interpreting">
    <div class="panel-heading" style="padding-bottom: 10px;">
        Interpreting
    </div>
    <div class="panel-body">

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms</th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>Interpreter 1</td>
                    <td>Day</td>
                    <td>CNY 5000.00</td>
                    <td>1</td>
                    <td>CNY 5000.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-interpreting"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Interpreter 2</td>
                    <td>Half Day</td>
                    <td>CNY 4000.00</td>
                    <td>1</td>
                    <td>CNY 4000.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-interpreting"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
        <div class="text-center">
            <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-interpreting">Add Iterm</a>
        </div>
    </div>
</div>

</div>

<div id="tab-2" class="tab-pane">
    <strong>Donec quam felis</strong>

    <p>Thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks,
        and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of
        the Almighty, who formed us in his own image, and the breath </p>

    <p>I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.
        I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect
        my talents. I should be incapable of drawing a single stroke at the present moment; and yet.</p>

</div>
</div>

</div>

</div>


</div>
</div>

<div class="alert alert-danger">
    Note: if the project status is Quote, then after click finish, the page go to quote_details page. if the status
    is Ordered, then go to project_details page.
</div>

</fieldset>



</form>
</div>
</div>
</div>

</div>

<script>
    var edit = function() {
        $('.click2edit').summernote({focus: true});
    };
    var save = function() {
        var aHTML = $('.click2edit').code(); //save HTML If you need(aHTML: array).
        $('.click2edit').destroy();
    };

</script>

<script>
    $(document).ready(function(){
        $('.dtbox').DateTimePicker();

        // trigger datetime picker when click to calendar icon
        // TODO: this is not working
        $('i.fa.fa-calendar').on('click', function(e){
            console.log('clicked');
            e.preventDefault();

            $(this).parents('.input-group').find('input[readonly]').click();
        });
    });
</script>