<!-- Le styles -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', []);")
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js')
?>

<div class="row">
<div class="col-lg-12">
<div class="ibox">
<div class="ibox-title">
    <h5><i class="fa fa-archive"></i> Create Project</h5>
</div>
<div class="ibox-content">

<form id="form" action="#" class="wizard-big">
<h1>Project Information</h1>
<fieldset>

<div class="ibox">
    <div class="ibox-title">
        <h5><i class="fa fa-puzzle-piece"></i> Project Type & Status</h5>
    </div>
    <div class="ibox-content">
        <div class="form-group">
            <label class="col-sm-3 control-label">
                <h4><i class="fa fa-coffee"></i>&nbsp; Translation</h4>
            </label>
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="translator" value="" /> Translation (No TM)
                </label>
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="proofreader" value="" /> Translation (Use TM)
                </label>
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="proofreader" value="" /> Proofreading
                </label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                <h4><i class="fa fa-desktop"></i> &nbsp;DTP/Engineering</h4>
            </label>
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="dtp" value="" /> DTP <i class="fa fa-apple"></i>
                </label>
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="dtp" value="" /> DTP <i class="fa fa-windows"></i>
                </label>
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="dtp" value="" /> Engineering</i>
                </label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                <h4><i class="fa fa-comments-o"></i> &nbsp; Interpreting</h4>
            </label>
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-primary">
                    <input type="radio" name="simul" value="" /> Simultaneous
                </label>
                <label class="btn btn-outline btn-primary">
                    <input type="radio" name="consec" value="" /> Consecutive
                </label>
                <label class="btn btn-outline btn-primary">
                    <input type="radio" name="bescort" value="" /> Business Escort
                </label>
                <label class="btn btn-outline btn-primary">
                    <input type="radio" name="tescort" value="" /> Tourism Escort
                </label>
            </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group" style="margin-bottom: 0px;">
            <label class="col-sm-3 control-label">
                <h4><i class="fa fa-cube"></i> &nbsp;Status</h4>
            </label>
            <div data-toggle="buttons">
                <!--
                <label class="btn btn-outline btn-warning">
                    <input type="radio" name="" value="" /> Quoting
                </label>
                -->
                <label class="btn btn-outline btn-info">
                    <input type="radio" name="" value="" /> Quote
                </label>
                <!-- quote = "quoted" by PM -->
                <label class="btn btn-outline btn-danger">
                    <input type="radio" name="" value="" /> Ordered
                </label>
                <!--
                <label class="btn btn-outline btn-primary">
                    <input type="radio" name="" value="" /> Ongoing
                </label>
                <label class="btn btn-outline btn-success">
                    <input type="radio" name="" value="" /> Reviewing
                </label>
                <label class="btn btn-outline btn-default">
                    <input type="radio" name="" value="" /> Completed
                </label>
                -->
            </div>
        </div>
    </div>
</div>

<div class="ibox">
    <div class="ibox-title">
        <h5><i class="fa fa-files-o"></i> Project Files </h5>
        <div class="ibox-tools">
            <a href="#" class="btn btn-xs btn-primary">Add files</a>
        </div>
    </div>
    <div class="ibox-content">
        <div class="row">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>File Name</th>
                    <th>File Size</th>
                    <th>Time Stamp</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td><a href="#"> 提高沼气PPTUltimase NRG - Sales Presentation.pdf</a></td>
                    <td>46.13 K</td>
                    <td> 2014-07-21 10:04:59 </td>
                    <td class="text-center">
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="ibox">
    <div class="ibox-title">
        <h5><i class="fa fa-list-ol"></i> Translation Languages</h5>
    </div>
    <div class="ibox-content">
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group form-horizontal">
                    <label class="col-sm-4 control-label">Source Language *</label>
                    <div class="col-sm-8">
                        <select class="form-control required valid" id="" name="" value="" aria-required="true">
                            <option>option 1</option>
                            <option>option 2</option>
                            <option>option 3</option>
                            <option>option 4</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label>Target Languages * &nbsp; </label>
                    <select class="form-control required multiselect" multiple="multiple">
                        <option value="cheese">Cheese</option>
                        <option value="tomatoes">Tomatoes</option>
                        <option value="mozarella">Mozzarella</option>
                        <option value="mushrooms">Mushrooms</option>
                        <option value="pepperoni">Pepperoni</option>
                        <option value="onions">Onions</option>
                        <option value="cheese">Cheese</option>
                        <option value="tomatoes">Tomatoes</option>
                        <option value="mozarella">Mozzarella</option>
                        <option value="mushrooms">Mushrooms</option>
                        <option value="pepperoni">Pepperoni</option>
                        <option value="onions">Onions</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="ibox">
    <div class="ibox-title">
        <h5><i class="fa fa-info-circle"></i> Project Information</h5>
    </div>
    <div class="ibox-content">
        <div class="row form-horizontal">
            <div class="row">
                <div class="col-lg-8">
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Reference *</label>
                        <div class="col-sm-9">
                            <input id="" name="" value="Project reference" type="text" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Priority *</label>
                        <div class="col-sm-8">
                            <div data-toggle="buttons">
                                <label class="btn btn-outline btn-primary btn-sm">
                                    <input type="radio" name="gender" value="male" /> Normal
                                </label>
                                &nbsp;
                                <label class="btn btn-outline btn-danger btn-sm">
                                    <input type="radio" name="gender" value="female" /> High
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6">
                <div class="form-group" id="ordered_date">
                    <label class="col-sm-3 control-label">Start Date *</label>
                    <div class="col-sm-9">
                        <div class="input-group date">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            <input type="text" class="form-control" value="03/04/2014" />
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">Field *</label>
                    <div class="col-sm-9">
                        <select class="form-control required valid" id="" name="" value="" aria-required="true">
                            <option>option 1</option>
                            <option>option 2</option>
                            <option>option 3</option>
                            <option>option 4</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">Sales </label>
                    <div class="col-sm-9">
                        <select class="form-control required valid" id="country" name="country" value=""
                                aria-required="true">
                            <option>option 1</option>
                            <option>option 2</option>
                            <option>option 3</option>
                            <option>option 4</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group" id="due_date">
                    <label class="col-sm-3 control-label">Due Date *</label>
                    <div class="col-sm-9">
                        <div class="input-group date">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            <input type="text" class="form-control" value="03/04/2014" />
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">Client *</label>
                    <div class="col-sm-9">
                        <select class="form-control required valid" id="" name="" value="" aria-required="true">
                            <option>option 1</option>
                            <option>option 2</option>
                            <option>option 3</option>
                            <option>option 4</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">PM *</label>
                    <div class="col-sm-9">
                        <select class="form-control required valid" id="" name="" value="" aria-required="true">
                            <option>option 1</option>
                            <option>option 2</option>
                            <option>option 3</option>
                            <option>option 4</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="row">

            <div class="form-group">
                <label class="col-sm-2 control-label">Interpreting Info </label>
                <div class="col-sm-10">
                    <input id="" name="" value="" type="text" class="form-control" />
                    <span class="help-block m-b-none">Interpreting only, put address/city/country information.</span>
                </div>
            </div>

        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Project Description </label>
            <div class="summernote">

            </div>
        </div>

    </div>
</div>

</fieldset>

<h1>Order Information</h1>
<fieldset>
<!-- here load the default service level for the client choosed previous step, if there is not price for the client,
then load PaperTask Price -->
<div class="ibox">
    <div class="ibox-title">
        <h4><i class="fa fa-sitemap"></i> Service Level <small>Project default service level</small></h4>
    </div>
    <div class="ibox-content wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-6">
                <div data-toggle="buttons">
                    <label class="btn btn-outline btn-primary">
                        <input type="radio" name="professional" value="" /> Professional
                    </label>
                    &nbsp;
                    <label class="btn btn-outline btn-primary">
                        <input type="radio" name="business" value="" /> Business
                    </label>
                    &nbsp;
                    <label class="btn btn-outline btn-primary">
                        <input type="radio" name="premium" value="" /> Premium
                    </label>
                </div>
            </div>
            <div class="col-lg-6 form-horizontal">
                <div class="form-group">
                    <label class="col-sm-6 control-label">Approximate duration *</label>
                    <div class="col-sm-3">
                        <input id="" name="" value="" type="text" class="form-control" />
                    </div>
                    <span class="col-sm-3 control-label">Working days</span>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="ibox">
<div class="ibox-title">
    <h4><i class="fa fa-file-text-o"></i> Order/Quote Information</h4>
</div>
<div class="ibox-content wrapper wrapper-content">
<div class="panel blank-panel">

<div class="panel-heading">
    <div class="panel-title m-b-md"><h4>Source Language - English</h4></div>
    <div class="panel-options">

        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#tab-1">Target Lang1</a></li>
            <li class=""><a data-toggle="tab" href="#tab-2">Target Lang2</a></li>
        </ul>
    </div>
</div>

<div class="panel-body">

<div class="tab-content">
<div id="tab-1" class="tab-pane active">

<div class="panel panel-default">
    <div class="panel-heading" style="padding-bottom: 10px;">
        Translation - <span class="text-info"><strong>Business</strong></span>
    </div>
    <div class="panel-body">

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms - <span class="text-info">Translation (No TM)</span></th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>uploaded file name 1 / or Task Name</td>
                    <td>Source Word</td>
                    <td>CNY 0.12</td>
                    <td>2000</td>
                    <td>CNY 240.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-translation-noTM"><i class="fa fa-edit"></i></a>
                        &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>uploaded file name 2 / or Task Name</td>
                    <td>Source Word</td>
                    <td>CNY 0.12</td>
                    <td>1000</td>
                    <td>CNY 120.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-translation-noTM"><i class="fa fa-edit"></i></a>
                        &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
        <div class="text-center">
            <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-translation-noTM">Add Iterm</a>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms - <span class="text-info">Translation (Use TM)</span></th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>2</td>
                    <td>Translation with TM</td>
                    <td>Source Word</td>
                    <td>CNY 0.12</td>
                    <td>1000</td>
                    <td>CNY 120.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-translation-TM"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;

                        <a data-toggle="collapse" href="#use_tm"><i class="fa fa-eye"></i></a>
                    </td>
                </tr>
                <tr>
                    <td colspan="7">
                        <div id="use_tm" class="panel-collapse collapse">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>TM Template</th>
                                        <th>Rate (%)</th>
                                        <th>Unit Price</th>
                                        <th>Quantity (Word)</th>
                                        <th>Quantity</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>Repetitions</td>
                                        <td>10%</td>
                                        <td>CNY 0.012</td>
                                        <td>100</td>
                                        <td>CNY 1.20</td>
                                    </tr>
                                    <tr>
                                        <td>100%</td>
                                        <td>10%</td>
                                        <td>CNY 0.012</td>
                                        <td>200</td>
                                        <td>CNY 2.40</td>
                                    </tr>
                                    <tr>
                                        <td>95%-99%</td>
                                        <td>10%</td>
                                        <td>CNY 0.012</td>
                                        <td>200</td>
                                        <td>CNY 2.40</td>
                                    </tr>
                                    <tr>
                                        <td>85%-94%</td>
                                        <td>50%</td>
                                        <td>CNY 0.06</td>
                                        <td>300</td>
                                        <td>CNY 18.00</td>
                                    </tr>
                                    <tr>
                                        <td>75%-84%</td>
                                        <td>50%</td>
                                        <td>CNY 0.06</td>
                                        <td>200</td>
                                        <td>CNY 12.00</td>
                                    </tr>
                                    <tr>
                                        <td>50%-74%</td>
                                        <td>100%</td>
                                        <td>CNY 0.12</td>
                                        <td>1000</td>
                                        <td>CNY 120.00</td>
                                    </tr>
                                    <tr>
                                        <td>No Match</td>
                                        <td>100%</td>
                                        <td>CNY 0.12</td>
                                        <td>1000</td>
                                        <td>CNY 120.00</td>
                                    </tr>
                                    <tr>
                                        <td colspan="4" align="right"><strong>Total</strong></td>
                                        <td class="text-info">CNY xxxx.xx</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading" style="padding-bottom: 10px;">
        Desktop Publishing
    </div>
    <div class="panel-body">

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms - <span class="text-info">DTP <i class="fa fa-apple"></i></span></th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>uploaded file name 1 / or Task Name</td>
                    <td>Page</td>
                    <td>CNY 10.00</td>
                    <td>10</td>
                    <td>CNY 100.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-dtp-mac"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>uploaded file name 2 / or Task Name</td>
                    <td>Source Word</td>
                    <td>CNY 50.00</td>
                    <td>2</td>
                    <td>CNY 100.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-dtp-mac"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
        <div class="text-center">
            <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-dtp-mac">Add Iterm</a>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms - <span class="text-info">DTP <i class="fa fa-windows"></i></span></th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>uploaded file name 1 / or Task Name</td>
                    <td>Page</td>
                    <td>CNY 10.00</td>
                    <td>10</td>
                    <td>CNY 100.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-dtp-pc"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>uploaded file name 2 / or Task Name</td>
                    <td>Hour</td>
                    <td>CNY 50.00</td>
                    <td>5</td>
                    <td>CNY 250.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-dtp-pc"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
        <div class="text-center">
            <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-dtp-pc">Add Iterm</a>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading" style="padding-bottom: 10px;">
        Engineering
    </div>
    <div class="panel-body">

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms</th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>uploaded file name 1 / or Task Name</td>
                    <td>Graphic</td>
                    <td>CNY 10.00</td>
                    <td>10</td>
                    <td>CNY 100.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-eng"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>uploaded file name 2 / or Task Name</td>
                    <td>Hour</td>
                    <td>CNY 50.00</td>
                    <td>2</td>
                    <td>CNY 100.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-eng"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
        <div class="text-center">
            <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-eng">Add Iterm</a>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading" style="padding-bottom: 10px;">
        Interpreting
    </div>
    <div class="panel-body">

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms</th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>Interpreter 1</td>
                    <td>Day</td>
                    <td>CNY 5000.00</td>
                    <td>1</td>
                    <td>CNY 5000.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-interpreting"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Interpreter 2</td>
                    <td>Half Day</td>
                    <td>CNY 4000.00</td>
                    <td>1</td>
                    <td>CNY 4000.00</td>
                    <td>
                        <a data-toggle="modal" href="#modal-interpreting"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                        <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
        <div class="text-center">
            <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-interpreting">Add Iterm</a>
        </div>
    </div>
</div>

</div>

<div id="tab-2" class="tab-pane">
    <strong>Donec quam felis</strong>

    <p>Thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks,
        and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of
        the Almighty, who formed us in his own image, and the breath </p>

    <p>I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.
        I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect
        my talents. I should be incapable of drawing a single stroke at the present moment; and yet.</p>

</div>
</div>

</div>

</div>


</div>
</div>

<div class="alert alert-danger">
    Note: if the project status is Quote, then after click finish, the page go to quote_details page. if the status
    is Ordered, then go to project_details page.
</div>

</fieldset>



</form>
</div>
</div>
</div>

</div>