
<!-- Le styles -->
<?php
$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/plugins/summernote/summernote-bs3.css' )
				  ->prependStylesheet ( $this->basePath () . '/css/plugins/summernote/summernote.css' )
?>

<!-- Scripts -->
<?php

$this->headScript ()->prependFile ( $this->basePath () . '/js/admin/employer/profile.js' )
					->prependFile ( $this->basePath () . '/js/admin/bootstrap-modal.js' )
					->prependScript ( "angularApp = angular.module('project', []);" )
					->prependFile ( $this->basePath () . '/js/plugins/summernote/summernote.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/validate/jquery.validate.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/steps/jquery.steps.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/pace/pace.min.js' )
					->prependFile ( $this->basePath () . '/js/inspinia.js' )?>
<style type="text/css">
.wizard-big.wizard>.content {
	min-height: 1200px;
}

.label {
	font-size: 15px;
}

h3 {
	font-size: 18px;
}

.float-e-margins .btn {
	margin-bottom: 0px;
}

.note-editor {
	height: 150px;
}
</style>
<div class="row" ng-controller="PapertaskEmployerEditController" ng-init="init('<?=$user["id"]; ?>','<?=$employer["id"]; ?>','<?= $user['country']?>', '<?= $employer['company']['id'];?>')" id="EmployerController">
	<div class="col-lg-12">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h3>
					<i class="fa fa-edit"></i> Edit Client Profile
				</h3>
			</div>
			<div class="ibox-content">
				<form id="form" action="">
					<!-- Basic Information -->
					<div class="panel panel-primary">
						<div class="panel-heading">
							<i class="fa fa-info-circle"> <strong>Basic Information</strong></i>
						</div>
						<div class="panel-body">
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label>Email *</label>
										<input type="text" class="form-control " value="<?php echo $user['email'];?>" disabled>
									</div>
									<div class="hr-line-dashed"></div>
									<div class="form-group">
										<label>First name *</label> 
										<input id="firstname" name="firstname" type="text" class="form-control required" value="<?php echo $user['firstName'];?>">
									</div>
									<div class="hr-line-dashed"></div>
									<div class="form-group">
										<label>Gender *</label>
										<div data-toggle="buttons">
											<label class="btn btn-outline btn-primary btn-sm <?php if ($user['gender'] == '0') {echo 'active';}?>"  ng-click="setGender('0')" > 
												<input type="radio" name="gender" > Male
											</label> &nbsp; <label
												class="btn btn-outline btn-primary btn-sm <?php if ($user['gender'] == '1') {echo 'active';}?>"  ng-click="setGender('1')"> 
												<input type="radio" name="gender"> Female
											</label>
										</div>
									</div>
									<div class="hr-line-dashed"></div>
									<div class="form-group">
										<label>City *</label> 
										<input id="city" name="city" type="text" class="form-control required" value="<?php echo $user['city'];?>">
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label>Username *</label> 
										<input id="username" name="userName" type="text" class="form-control " value="<?php echo $employer['name'];?>" disabled>
									</div>
									<div class="hr-line-dashed"></div>
									<div class="form-group">
										<label>Last name *</label> 
										<input id="lastname" name="surname" type="text" class="form-control required" value="<?php echo $user['lastName'];?>">
									</div>
									<div class="hr-line-dashed"></div>
									<div class="form-group">
										<label>Phone *</label> 
										<input id="phone" name="phone" type="phone" class="form-control required" value="<?php echo $user['phone'];?>">
									</div>
									<div class="hr-line-dashed"></div>
									<div class="form-group">
										<label>Country *</label> 
										<select class="form-control required" id="country" name="country" ng-model="employer.country" ng-options="country.label for country in countries">																						
										</select>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Company Information -->
					<div class="panel panel-primary">
						<div class="panel-heading">
							<i class="fa fa-building"> <strong>Company Information</strong></i>
						</div>
						<div class="panel-body">
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label>Position </label> 
										<input id="position" name="position" type="text" class="form-control" value="<?php echo $employer['position']?>">
									</div>
					
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label>Company </label> 
										<select class="form-control required" id="company" name="company" ng-model="employer.company" ng-options="company.name for company in companies">											
										</select> <span class="help-block m-b-none"> &nbsp;Not in the
											list? Please <a data-toggle="modal" class="text-info"
											href="#modal-company">create a new company</a>.
										</span>
									</div>
								</div>
								<input type="hidden" id="defaultServiceLevel" value="<?php echo $employer['defaultServiceLevel'];?>">
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-sm-4 col-sm-offset-4">
							<button class="btn btn-primary btn-block" type="submit" ng-click='submit();'>Save</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<?php include "edit/modal.phtml" ?>
<script type="text/javascript">
$(document).ready(function() {
	$(".summernote").summernote();
});
var edit = function() {
	$(".summernote").summernote({focus: true});
}
</script>