
<!-- Scripts -->
<?php

$this->headScript ()->prependFile ( $this->basePath () . '/js/admin/employer/list.js' )
					->prependFile ( $this->basePath () . '/js/admin/bootstrap-modal.js' )
					->prependScript ( "angularApp = angular.module('project', []);" )
					->prependFile ( $this->basePath () . '/js/plugins/summernote/summernote.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/validate/jquery.validate.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/steps/jquery.steps.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/pace/pace.min.js' )
					->prependFile ( $this->basePath () . '/js/inspinia.js' )?>
					
<div class="row" ng-controller="PapertaskEmployerListController" ng-init="init()">
	<div class="col-lg-12">
		<div class="wrapper wrapper-content animated fadeInUp">

			<div class="ibox">
				<div class="ibox-title">
					<h5>Clients</h5>
					<div class="ibox-tools">
						<a data-toggle="collapse" href="#search_freelancer" class="btn btn-primary btn-xs"><i class="fa fa-search"></i> Search</a>
					</div>
				</div>

				<div class="ibox-content">
					<div class="row">
						<div class="col-lg-12">
							<div id="search_freelancer" class="panel-collapse collapse faq-answer">
								<form class="form-horizontal">
									<div class="row">
										<div class="col-lg-4">
											<div class="form-group">
												<label class="col-sm-3 control-label">Name</label>
												<div class="col-sm-9"><input type="text" class="form-control"></div>
											</div>
											<div class="form-group">
												<label class="col-sm-3 control-label">Company</label>
												<div class="col-sm-9"><input type="text" class="form-control"></div>
											</div>
											<div class="form-group">
												<label class="col-sm-2 control-label"></label>
												<div class="col-sm-10">
													<label class="checkbox-inline"> 
														<input type="checkbox" value="option1" id="unactive"> &nbsp;&nbsp;&nbsp;<strong>Include unactive account </strong>
													</label> 
												</div>
											</div>
										</div>
										<div class="col-lg-4">
											<div class="form-group">
												<label class="col-sm-3 control-label">ID</label>
												<div class="col-sm-9"><input type="text" class="form-control"></div>
											</div>
											<div class="form-group">
												<label class="col-sm-3 control-label">Country</label>
												<div class="col-sm-9">
													<select class="form-control" name="">
														<option value=""></option>
														<option ng-repeat="country in countries" ng-value="country">{{country.label}}</option>													  
													</select>
												</div>
											</div>
										</div>
										<div class="col-lg-4">
											<div class="form-group">
												<label class="col-sm-3 control-label">Email</label>
												<div class="col-sm-9"><input type="text" class="form-control"></div>
											</div>
											<div class="form-group">
												<label class="col-sm-3 control-label">Currency</label>
												<div class="col-sm-9">
													<select class="form-control" name="">
													  <option></option>
													  <option value="cny">CNY</option>
													  <option value="usd">USD</option>
													</select>
												</div>
											</div>
										</div>
									</div>
									<div class="text-right tooltip-demo">
										<a href="#" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Search</a>
										<a href="#" class="btn btn-white btn-sm" type="reset"><i class="fa fa-times"></i> Reset</a>
									</div>
								</form>
							</div>
						</div>
					</div>

					<div class="project-list">
						<table class="table table-hover">
							<tbody>
								<tr ng-repeat="employer in employers">
									<td class="project-status" width="1%">
										<span ng-if="employer.isActive=='1'" class="label label-primary">Active</span>
										<span  ng-if="employer.isActive=='0'" class="label label-default">Unactive</span>
									</td>
									<td class="project-title">
										<strong><i class="fa fa-user"></i> {{employer.lastName}}&nbsp;{{employer.firstName}}</strong>
										<br/>
										<small>Created {{employer.createdTime}}</small>
									</td>
									<td class="project-title">
										<strong><i class="fa fa-envelope"></i> {{employer.email}}</strong>
										<br/>
										<small>Marketing Manager</small>
									</td>
									<td class="project-title">
										<strong><i class="fa fa-building"></i> IBM</strong>
										<br/>
										<small>{{getCountry(employer.country)}}</small>
									</td>
									<td class="project-completion">
										<strong><i class="fa fa-tasks"></i> Tasks done: 88</strong>
										<br />
										<small>Currency: <i class="fa fa-{{employer.currency}}"></i></small>
									</td>
									<td class="project-actions">
										<span class="btn btn-white btn-sm" ng-click="onViewClicked(employer.id)"><i class="fa fa-folder"></i> View </span>
										<span class="btn btn-white btn-sm" ng-click="onEditClicked(employer.id)"><i class="fa fa-pencil"></i> Edit </span>
										<span class="btn btn-danger btn-sm" ng-click="onDeleteClicked(employer.id)"><i class="fa fa-trash"></i> Delete </span> <!-- only admin has right to show the delete button -->
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="btn-group text-right">
				        <button type="button" class="btn btn-white" ng-class="pages.previous?'':'disabled'" ng-click="onBtnPreviousClicked()"><i class="fa fa-chevron-left"></i></button>
				        <button ng-repeat="page in pages.pagesInRange" class="btn btn-white" ng-class="page==pages.current?'active':''" ng-click="onBtnGoto(page)">{{page}}</button>
						<button type="button" class="btn btn-white"	ng-class="pages.next?'':'disabled'" ng-click="onBtnNextClicked()"><i class="fa fa-chevron-right"></i></button>						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
 
<?php include "new/modal.phtml" ?>