
<!-- add language pair and price -->
<div id="modal-translation" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Language pairs and prices</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Source Language *</label>
                                <select class="form-control required" id="sourceLanguage" name="sourceLanguage"
                                        ng-model="translationPrice"
                                        ng-options="language.name for language in languages">
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Target Language *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Price/word *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-w-m btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-w-m btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- add DTP price -->
<div id="modal-dtp" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Add DTP prices</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Languages *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option>European/CE/Greek/Russian</option>
                                    <option>SC/TC/JP/KO</option>
                                    <option>TH/VN</option>
                                    <option>Others</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>DTP software *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Price/Page (MAC) *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                            <div class="form-group">
                                <label>Price/Page (PC) *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                            <div class="form-group">
                                <label>Price/Hour (MAC) *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                            <div class="form-group">
                                <label>Price/Hour (PC) *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-w-m btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-w-m btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- add interpreting price -->
<div id="modal-interpreting" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Interpreting prices</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Source Language *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Target Language *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Interpreting Service *</label>
                                <select class="form-control required" id="country" name="country" value="">
                                    <option></option>
                                    <option>Simultaneous</option>
                                    <option>Consecutive</option>
                                    <option>Business</option>
                                    <option>Tourist</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Price/Day *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                            <div class="form-group">
                                <label>Price/Half-day *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-w-m btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-w-m btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>