<h1>Resource Type</h1>
<fieldset>
    <p>Please choose your resource type. You should at least select one of the below service type.</p>

    <div class="panel panel-primary">
        <div class="panel-body">
            <h2><i class="fa fa-coffee"></i>&nbsp; Translation</h2>
            <br />
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="translator" value="" /> Translator
                </label>
                &nbsp;
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="proofreader" value="" /> Proofreader
                </label>
            </div>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-body">
            <h2><i class="fa fa-desktop"></i> &nbsp;Desktop Publishing</h2>
            <br />
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="dtp" value="" /> Desktop Publishing
                </label>
            </div>
        </div>
    </div>

    <div class="panel panel-success">
        <div class="panel-body">
            <h2><i class="fa fa-comments-o"></i> &nbsp; Interpreting</h2>
            <br />
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="simul" value="" /> Simultaneous
                </label>
                &nbsp;
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="consec" value="" /> Consecutive
                </label>
                &nbsp;
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="bescort" value="" /> Business Escort
                </label>
                &nbsp;
                <label class="btn btn-outline btn-primary">
                    <input type="checkbox" name="tescort" value="" /> Tourism Escort
                </label>
            </div>
        </div>
    </div>
</fieldset>