<h1>Resource Type</h1>
<fieldset class="resource-types">
    <p>Please choose your resource type. You should at least select one of the below service type.</p>

    <div class="panel panel-primary" ng-repeat="resourceGroup in resources">
        <div class="panel-body">
            <h2><i class="fa fa-coffee"></i>&nbsp; {{resourceGroup.group.name}}</h2>
            <br />
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-primary {{resource_active[resource.id]}}"
                       ng-repeat="resource in resourceGroup.resources" ng-click="toggleResource(resource.id)">
                    <input type="checkbox" name="resource_{{resource.id}}"
                           ng-value="resource.id"/> {{resource.name}}
                </label>
            </div>
        </div>
    </div>
</fieldset>