<?php echo $this->doctype(); ?>
<html lang="en" ng-app="project">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle()->setSeparator(' | ')->prepend($this->translate('PaperTask'))->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->appendStylesheet($this->basePath() . '/css/style.css')
        ->appendStylesheet($this->basePath() . '/css/custom.css')
        ->prependStylesheet($this->basePath() . '/css/animate.css')
        ->prependStylesheet($this->basePath() . '/css/plugins/iCheck/custom.css')
        ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/common.js')
        ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
        ->prependFile($this->basePath() . '/js/inspinia.js')
        ->prependFile($this->basePath() . '/js/plugins/slimscroll/jquery.slimscroll.min.js')
        ->prependFile($this->basePath() . '/js/plugins/metisMenu/jquery.metisMenu.js')
        ->prependFile($this->basePath() . '/js/plugins/angular-file-upload/angular-file-upload.js')
        ->prependFile($this->basePath() . '/js/plugins/console-sham/console-sham.js')
        ->prependFile($this->basePath() . '/js/angular.min.js')
        ->prependFile("http://nervgh.github.io/js/es5-sham.min.js")
        ->prependFile("http://nervgh.github.io/js/es5-shim.min.js")
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery-1.10.2.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>
<div id="wrapper">

    <!-- Left sidebar -->
    <?php include "admin/left-sidebar.phtml" ?>
    <!-- End left sidebar -->

    <!-- Main Wrapper -->
    <div id="page-wrapper" class="gray-bg">

        <!-- Top Nav -->
        <div class="row border-bottom">
            <?php include "admin/top-nav.phtml" ?>
        </div><!-- End Top Nav -->

        <div class="wrapper wrapper-content">
            <div class="row">
                <div class="col-lg-12">
                    <!-- Flash Messenger -->
                    <?php
                    $flash = $this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                 &times;
                             </button>
                             <ul><li>')
                        ->setMessageSeparatorString('</li><li>')
                        ->setMessageCloseString('</li></ul></div>');

                    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
                    echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
                    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                    ?><!-- End Flash Messenger -->
                </div>
            </div>
            <?php echo $this->content ?>
        </div>

        <!-- Footer -->
        <div class="footer">
            <div class="pull-right">
                10GB of <strong>250GB</strong> Free.
            </div>
            <div>
                <strong>Copyright</strong> Example Company &copy; 2014-2015
            </div>
        </div><!-- End Footer -->
    </div><!-- End Main Wrapper -->
</div>

<?php echo $this->inlineScript() ?>
<script>if(typeof(angular) != 'undefined' && typeof(angularApp) == 'undefined'){
        var angularApp = angularApp || angular.module('project', []);
    }</script>
</body>
</html>
