<form method="" class="form-horizontal">
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                <label class="col-sm-3 control-label"> ID</label>
                <div class="col-sm-9"><input type="text" class="form-control"></div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Source</label>
                <div class="col-sm-9">
                    <select class="form-control" name="">
                        <option></option>
                        <option value="">Admin</option>
                        <option value="">General Manager</option>
                        <option value=""></option>
                        <option value="">Financial Manager</option>
                        <option value=""></option>
                        <option value="">Sales Director</option>
                        <option value="">Sales</option>
                        <option value=""></option>
                        <option value="">Operation Manager</option>
                        <option value="">Project Manager</option>
                        <option value="">In-house Translator</option>
                        <option value="">In-house Editor/Proofreader</option>
                        <option value="">In-house DTP</option>
                        <option value="">In-house Engineering</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Order</label>
                <div class="col-sm-9">
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        <input type="text" class="form-control" value="">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label"> Client ID</label>
                <div class="col-sm-9"><input type="text" class="form-control"></div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">PM</label>
                <div class="col-sm-9">
                    <select class="form-control" name="">
                        <option></option>
                        <option value="">Admin</option>
                        <option value="">General Manager</option>
                        <option value=""></option>
                        <option value="">Financial Manager</option>
                        <option value=""></option>
                        <option value="">Sales Director</option>
                        <option value="">Sales</option>
                        <option value=""></option>
                        <option value="">Operation Manager</option>
                        <option value="">Project Manager</option>
                        <option value="">In-house Translator</option>
                        <option value="">In-house Editor/Proofreader</option>
                        <option value="">In-house DTP</option>
                        <option value="">In-house Engineering</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                <label class="col-sm-3 control-label">Reference</label>
                <div class="col-sm-9"><input type="text" class="form-control"></div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Target</label>
                <div class="col-sm-9">
                    <select class="form-control" name="">
                        <option></option>
                        <option value="">Admin</option>
                        <option value="">General Manager</option>
                        <option value=""></option>
                        <option value="">Financial Manager</option>
                        <option value=""></option>
                        <option value="">Sales Director</option>
                        <option value="">Sales</option>
                        <option value=""></option>
                        <option value="">Operation Manager</option>
                        <option value="">Project Manager</option>
                        <option value="">In-house Translator</option>
                        <option value="">In-house Editor/Proofreader</option>
                        <option value="">In-house DTP</option>
                        <option value="">In-house Engineering</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Completed</label>
                <div class="col-sm-9">
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        <input type="text" class="form-control" value="">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label"> Company</label>
                <div class="col-sm-9"><input type="text" class="form-control"></div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Sales</label>
                <div class="col-sm-9">
                    <select class="form-control" name="">
                        <option></option>
                        <option value="">Admin</option>
                        <option value="">General Manager</option>
                        <option value=""></option>
                        <option value="">Financial Manager</option>
                        <option value=""></option>
                        <option value="">Sales Director</option>
                        <option value="">Sales</option>
                        <option value=""></option>
                        <option value="">Operation Manager</option>
                        <option value="">Project Manager</option>
                        <option value="">In-house Translator</option>
                        <option value="">In-house Editor/Proofreader</option>
                        <option value="">In-house DTP</option>
                        <option value="">In-house Engineering</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                <label class="col-sm-3 control-label">Field</label>
                <div class="col-sm-9">
                    <select class="form-control" name="">
                        <option></option>
                        <option value="">Admin</option>
                        <option value="">General Manager</option>
                        <option value=""></option>
                        <option value="">Financial Manager</option>
                        <option value=""></option>
                        <option value="">Sales Director</option>
                        <option value="">Sales</option>
                        <option value=""></option>
                        <option value="">Operation Manager</option>
                        <option value="">Project Manager</option>
                        <option value="">In-house Translator</option>
                        <option value="">In-house Editor/Proofreader</option>
                        <option value="">In-house DTP</option>
                        <option value="">In-house Engineering</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Status</label>
                <div class="col-sm-9">
                    <select class="form-control" name="">
                        <option></option>
                        <option value="">Ordered</option>
                        <option value="">Ongoing</option>
                        <option value="">Reviewing</option>
                        <option value="">Completed</option>
                        <option value="">Rejected</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Pay Status</label>
                <div class="col-sm-9">
                    <select class="form-control" name="">
                        <option></option>
                        <option value="">Paid</option>
                        <option value="">Unpaid</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="text-right tooltip-demo">
        <a href="#" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Search</a>
        <a href="#" class="btn btn-white btn-sm" type="reset"><i class="fa fa-times"></i> Reset</a>
    </div>
</form>