<?php echo $this->headTitle($this->translate('Edit Payment Information')) ?>

<?php
$this->headScript()
    ->prependFile($this->basePath() . '/js/admin/freelancer/edit-bank-info.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependScript("angularApp = angular.module('project', []);");
$this->inlineScript()
    ->prependScript("
        var USER_ID = '" . $this->user['id'] . "';
    ");
?>
<div ng-controller="editBankInfoController" class="ibox float-e-margins">
    <div class="ibox-title">
        <h4><i class="fa fa-edit"></i> <?php echo $this->translate('Edit Payment Information') ?></h4>
    </div>

    <div class="ibox-content">
        <form name="editBankInfo" method="">
            <input type="hidden" ng-model="bankInfo.id" />

            <div class="panel panel-primary">
                <div class="panel-body">
                    <p class="alert alert-success alert-dismissable" ng-show="updated">
                        <?php echo $this->translate('Your bank information has been updated') ?>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                            &times;
                        </button>
                    </p>
                    <?php include __DIR__ . "/../user/bank-info.phtml" ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4 col-sm-offset-4">
                    <button ng-click="submit()" class="btn btn-primary btn-block" type="submit">
                        <?php echo $this->translate('Save') ?></button>
                </div>
            </div>

        </form>
    </div>
</div>