<?php echo $this->headTitle($this->translate('Edit Payment Information')) ?>

<?php
$this->headScript()
    ->prependFile($this->basePath() . '/js/admin/freelancer/edit-bank-info.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependScript("angularApp = angular.module('project', []);");
$this->inlineScript()
    ->prependScript("
        var USER_ID = '" . $this->user['id'] . "';
    ");
?>
<div ng-controller="editBankInfoController" class="ibox float-e-margins">
    <div class="ibox-title">
        <h4><i class="fa fa-edit"></i> <?php echo $this->translate('Edit Payment Information') ?></h4>
    </div>

    <div class="ibox-content">
        <form name="editBankInfo" method="">
            <input type="hidden" ng-model="bankInfo.id" />

            <div class="panel panel-primary">
                <div class="panel-body">
                    <p class="alert alert-success alert-dismissable" ng-show="updated">
                        <?php echo $this->translate('Your bank information has been updated') ?>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                            &times;
                        </button>
                    </p>
                    <h4><i class="fa fa-bank"></i> <?php echo $this->translate('Payment Information') ?></h4>
                    <div class="hr-line-dashed"></div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label><?php echo $this->translate('Paypal') ?></label>
                                <input id="paypal" ng-model="bankInfo.paypal" name="paypal" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label><?php echo $this->translate('Alipay') ?></label>
                                <input id="alipay" ng-model="bankInfo.alipay" name="alipay" type="text" class="form-control required">
                            </div>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label><?php echo $this->translate('Bank Account') ?></label>
                                <input ng-model="bankInfo.account" name="bank_name" value="" type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label><?php echo $this->translate('Bank Address') ?></label>
                                <input ng-model="bankInfo.address" name="bank_address" value="" type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label><?php echo $this->translate('Bank City') ?></label>
                                <input ng-model="bankInfo.city" name="bank_city" value="" type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label><?php echo $this->translate('Bank Country') ?></label>
                                <input ng-model="bankInfo.country" name="bank_country" value="" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label><?php echo $this->translate('Beneficiar Name') ?></label>
                                <input ng-model="bankInfo.name" name="beneficiar" value="" type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label><?php echo $this->translate('Account No./IBAN') ?></label>
                                <input ng-model="bankInfo.accountNo" name="account_no" value="" type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label><?php echo $this->translate('Swift Code') ?></label>
                                <input ng-model="bankInfo.swift" name="swift" value="" type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label><?php echo $this->translate('ABA Routing Number') ?></label>
                                <input ng-model="bankInfo.routingNumber" name="aba" value="" type="text" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4 col-sm-offset-4">
                    <button ng-click="submit()" class="btn btn-primary btn-block" type="submit">
                        <?php echo $this->translate('Save') ?></button>
                </div>
            </div>

        </form>
    </div>
</div>