<?php $this->headTitle($this->translate('Freelancers')) ?>
<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/admin/freelancer/index.js')
    ->prependScript("angularApp = angular.module('project', []);")
    ->prependFile($this->basePath() . '/js/inspinia.js')
?>
<div class="ibox" id="mainController" ng-controller="listFreelancerController">
<div class="ibox-title">
    <h5><?php echo $this->translate('Freelancers') ?></h5>

    <div class="ibox-tools">
        <a data-toggle="collapse" href="#search_freelancer" class="btn btn-primary btn-xs"><i class="fa fa-search"></i>
            Search</a>
    </div>
</div>

<div class="ibox-content">
    <div class="row">
        <div class="col-lg-12">
            <div id="search_freelancer" class="panel-collapse collapse faq-answer">
                <form method="" class="form-horizontal">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Name</label>

                                <div class="col-sm-9"><input type="text" class="form-control"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Type</label>

                                <div class="col-sm-9">
                                    <select class="form-control" name="">
                                        <option></option>
                                        <option value="">Translation</option>
                                        <option value="">Interpreting</option>
                                        <option value="">Desktop Publishing</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Rating</label>

                                <div class="col-sm-9">
                                    <select class="form-control" name="">
                                        <option></option>
                                        <option value="">A+</option>
                                        <option value="">A</option>
                                        <option value="">A-</option>
                                        <option value="">B+</option>
                                        <option value="">B</option>
                                        <option value="">B-</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"></label>

                                <div class="col-sm-10">
                                    <label class="checkbox-inline">
                                        <input type="checkbox" value="option1" id="unactive"> &nbsp;&nbsp;&nbsp;<strong>Include
                                            unactive account </strong>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">ID</label>

                                <div class="col-sm-9"><input type="text" class="form-control"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Source</label>

                                <div class="col-sm-9">
                                    <select class="form-control" name="">
                                        <option></option>
                                        <option value="">Translation</option>
                                        <option value="">Interpreting</option>
                                        <option value="">Desktop Publishing</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Specialism</label>

                                <div class="col-sm-9">
                                    <select class="form-control" name="">
                                        <option></option>
                                        <option value="">A+</option>
                                        <option value="">A</option>
                                        <option value="">A-</option>
                                        <option value="">B+</option>
                                        <option value="">B</option>
                                        <option value="">B-</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"></label>

                                <div class="col-sm-10">
                                    <label class="checkbox-inline">
                                        <input type="checkbox" value="option1" id="unactive"> &nbsp;&nbsp;&nbsp;<strong>Specialism
                                            tested </strong>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Email</label>

                                <div class="col-sm-9"><input type="text" class="form-control"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Target</label>

                                <div class="col-sm-9">
                                    <select class="form-control" name="">
                                        <option></option>
                                        <option value="">Translation</option>
                                        <option value="">Interpreting</option>
                                        <option value="">Desktop Publishing</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Country</label>

                                <div class="col-sm-9">
                                    <select class="form-control" name="">
                                        <option></option>
                                        <option value="">Translation</option>
                                        <option value="">Interpreting</option>
                                        <option value="">Desktop Publishing</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"></label>

                                <div class="col-sm-10">
                                    <label class="checkbox-inline">
                                        <input type="checkbox" value="option1" id="unactive"> &nbsp;&nbsp;&nbsp;<strong>Senior
                                            account </strong>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="text-right tooltip-demo">
                        <a href="#" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Search</a>
                        <a href="#" class="btn btn-white btn-sm" type="reset"><i class="fa fa-times"></i> Reset</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="project-list">
        <table class="table table-hover">
            <tbody>
            <tr ng-repeat="user in list">
                <td class="project-status" width="1%">
                    <span class="label {{user.isActive ? 'label-primary' : 'label-default'}}">
                        {{user.isActive ? 'Active' : 'Unactive'}}
                    </span>
                </td>
                <td class="project-title">
                    <strong><i class="fa fa-user"></i> {{user.lastName}}, {{user.firstName}}</strong>
                    <br/>
                    <small>Created {{ user.createdTime }}</small>
                </td>
                <td class="project-title">
                    <strong><i class="fa fa-envelope"></i> {{user.email}}</strong>
                    <br/>
                    <small>{{user.country}}</small>
                </td>
                <td class="project-completion">
                    <!-- TODO: need to add tasksDone and rating here -->
                    <small><i class="fa fa-tasks"></i> Tasks done: {{user.tasksDone}}</small>
                    <br/>
                    <small>Rating: <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i
                            class="fa fa-star"></i><i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i></small>
                </td>
                <td class="project-actions">
                    <a href="#" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> View </a>
                    <a href="#" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> Edit </a>
                    <a href="#" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Delete </a>
                    <!-- only admin has right to show the delete button -->
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="pager btn-group text-right">
        <button type="button" data-page="{{pages.current - 1}}"
                class="btn btn-white"><i class="fa fa-chevron-left"></i></button>
        <button ng-repeat="n in rangeCustom" data-page="{{n+1}}"
                class="btn btn-white{{(n+1==pages.current) ? ' active' : ''}}">{{n + 1}}</button>
        <buttondata-page="{{pages.current + 1}}"  type="button"
            class="btn btn-white"><i class="fa fa-chevron-right"></i></button>
    </div>
</div>
</div>