<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            <div class="jumbotron">
                <h1>Please login your email and confirm</h1>
                <p>We have sent an confirmation email to your email: xxx@xx.com</p>
                <p>If you do not see the confirmation email in you INBOX, please check your JUNK mail.</p>
            </div>
        </div>

    </div>
</div>