<?php $this->headTitle('Customer registration') ?>
<div class="middle-box text-center loginscreen   animated fadeInDown">
    <h3><?php echo $this->translate('Customer registration') ?></h3>

    <p><?php echo $this->translate('I need translation services.') ?></p>

    <form class="m-t" role="form" action="<?php echo $this->url('user') ?>/register/createPost">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Last Name" required="">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="First Name" required="">
        </div>
        <div class="form-group">
            <input type="email" class="form-control" placeholder="Email" required="">
        </div>
        <div class="form-group">
            <input type="phone" class="form-control" placeholder="Phone" required="">
            <span class="help-block m-b-none text-left">&nbsp; Country code + phone number.</span>
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" required="">
        </div>
        <div class="form-group">
            <div class="checkbox i-checks"><label> <input type="checkbox"><i></i> &nbsp;Agree the <a href="terms.html"
                                                                                                     class="color-green">Terms
                        and Conditions.</a> </label></div>

        </div>
        <button type="submit" class="btn btn-primary block full-width m-b">Register</button>
        <h3>or Sign up with</h3>

        <div class="col-lg-12 well">
            <a class="btn btn-success btn-facebook">
                <i class="fa fa-facebook"> </i> Facebook
            </a> &nbsp;&nbsp;
            <a class="btn btn-danger btn-google">
                <i class="fa fa-google"> </i> Google
            </a>
        </div>

        <p class="text-muted text-center">
            <small>Already have an account?</small>
        </p>
        <a class="btn btn-sm btn-white btn-block" href="login.html">Login</a>
    </form>

</div>
<?php $this->headScript()->appendFile($this->basePath() . '/js/plugins/iCheck/icheck.min.js') ?>
<?php
$this->inlineScript()->appendScript('
    $(document).ready(function () {
        $(".i-checks").iCheck({
            checkboxClass: "icheckbox_square-green",
            radioClass: "iradio_square-green",
        });
    });
');
?>