
<!-- Translation no TM -->
<div id="modal-translation-noTM" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Input/Edit Word Count</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>File Name / Task Name *</label>
                                <input id="phone" name="phone" type="phone" value="here load uploaded source file name" class="form-control required">
                            </div>
                            <div class="form-group">
                                <label>Rate *</label>
                                <input id="phone" name="phone" type="phone" value="here load client price depends on level" class="form-control required">
                            </div>
                            <div class="form-group">
                                <label>Quantity *</label>
                                <input id="phone" name="phone" type="phone" value="" class="form-control required">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-w-m btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-w-m btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- Translation TM -->
<div id="modal-translation-TM" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Input/Edit Word count</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Iterm's Name</label>
                                <div class="col-sm-9">
                                    <input id="phone" name="phone" type="phone" value="Translation with TM" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Rate</label>
                                <div class="col-sm-9">
                                    <input id="phone" name="phone" type="phone" value="0.12" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Repetitions</label> <!-- word counts -->
                                <div class="col-sm-9">
                                    <input id="phone" name="phone" type="phone" value="100" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">100% </label>
                                <div class="col-sm-9">
                                    <input id="phone" name="phone" type="phone" value="200" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">95%-99% </label>
                                <div class="col-sm-9">
                                    <input id="phone" name="phone" type="phone" value="200" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">85%-94% </label>
                                <div class="col-sm-9">
                                    <input id="phone" name="phone" type="phone" value="300" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">75%-84% </label>
                                <div class="col-sm-9">
                                    <input id="phone" name="phone" type="phone" value="200" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">50%-74% </label>
                                <div class="col-sm-9">
                                    <input id="phone" name="phone" type="phone" value="1000" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">No Match </label>
                                <div class="col-sm-9">
                                    <input id="phone" name="phone" type="phone" value="1000" class="form-control">
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-w-m btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-w-m btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
